"""CO-Bench-style config for the Multi-Base Tugboat Routing and Scheduling
Problem (MTRSP-MB).

This file is the single source of truth that the cobench spec builder consumes.

  - DESCRIPTION  → spec.description (LLM prompt: problem statement)
  - solve()      → spec.starter_code (LLM prompt: function signature + I/O schema)
  - load_data()  → spec.load_data (parses one .txt instance file → [instance_dict])
  - eval_func()  → spec.tools.is_feasible + spec.tools.objective (its SOURCE is
                   shown verbatim in the LLM prompt's feasibility section, so it
                   doubles as the constraint specification).

MTRSP-MB is a hand-authored CO-Bench problem (no reference paper / known
optima), generated by
problems/cobench/multi_base_tugboat_routing_and_scheduling_problem/build_instances.py.
"""

import ast


DESCRIPTION = """\
Multi-Base Tugboat Routing and Scheduling Problem with Origin Return (MTRSP-MB)

At a port operating over a continuous horizon of T_max hours, n tasks
(berthing / unberthing operations) need to be served by m tugboats based at
p different bases. Each task may require collaborative service by multiple
tugboats, has a time window, a horsepower requirement, and a fixed service
duration. Each tugboat belongs to a specific home base and MUST depart from
and return to that same base — it cannot use any other base.

A defining property: you may CHOOSE TO LEAVE SOME TASKS UNSERVED. That is a
legal decision; it simply forfeits servicing that task at the cost of a large
per-task penalty W (= penalty_weight, typically 10000). The decision space
therefore covers BOTH "which tasks to serve" AND "how to route + schedule the
tugboats that serve them". Doing nothing (zero tasks served) is feasible —
just expensive (Z = W·n).

────────────────────────────────────────────────────────────
Notation
────────────────────────────────────────────────────────────
  Tasks         S = {1, 2, …, n}                (1-indexed; matches paper)
  Tugboats      K = {0, 1, …, m-1}              (0-indexed; matches list positions)
  Bases         B = {-1, -2, …, -p}             (negative ints; the home base of
                                                  tugboat k is tugboat_base_assignment[k])
  Base nodes    Base b's destination = n - b    (positive, e.g. -1 → n+1)

Per tugboat k ∈ K, the home base is fixed by `tugboat_base_assignment[k]` and
the set K_b ⊆ K of tugboats belonging to base b is implicit.

────────────────────────────────────────────────────────────
Decisions (continuous time τ_s ∈ ℝ≥0; binary z_s, y_sk, x_ij^k)
────────────────────────────────────────────────────────────
For each task s ∈ S, either leave s unserved (z_s = 0), OR commit to:
  • a START TIME τ_s ∈ [a_s, b_s] with τ_s + T_s ≤ T_max (C10, C11)
  • a non-empty SET of serving tugboats T_s ⊆ K, |T_s| ≤ Γ_s,
    with total horsepower Σ_{k∈T_s} HP_k ≥ H_s^min (C1, C2)
  • for each serving tugboat k ∈ T_s, a position for task s inside that
    tugboat's ordered ROUTE — tug k's route starts at home base, visits
    one or more tasks in order, and ends at its home base's destination
    node (C3, C4, C9)

All tugboats serving task s MUST arrive at τ_s and depart at τ_s + T_s
(C9/C10 same-start are implicit because τ_s is a single value).

The full multi-objective decision is captured by:
  • routes[k]               ordered list of task ids served by tugboat k
                            (empty list = tug k is unused; routes[k]
                             implicitly = [home_base_k, task_1, …, task_L, dest_k])
  • task_tugboats[s]        list of tugboat ids that serve task s
                            (only present if z_s = 1)
  • task_start_times[s]     τ_s (only present if z_s = 1)

A task is served (z_s = 1) iff s appears in task_tugboats and
task_start_times. The set of executed tasks equals the union of all routes
and equals task_tugboats.keys() and equals task_start_times.keys().

────────────────────────────────────────────────────────────
Objective:   minimize   Z = Z_fuel + W · Z_penalty
(LOWER IS BETTER)
────────────────────────────────────────────────────────────

  Z_fuel = Z_service + Z_transit
       Fuel consumed across all tugboats. Has two parts:

       Z_service = Σ_{s∈executed} Σ_{k∈T_s} α_k · HP_k · T_s
         — fuel each serving tug burns while doing the service. α_k is the
           tug-specific service-mode burn rate (kg per kW·h).

       Z_transit = Z_out + Z_mid + Z_in
         — fuel each tug burns while moving:
           • Z_out: from home base to first task on its route
           • Z_mid: between consecutive tasks on its route
           • Z_in:  from last task back to home base's destination node
           β_k is the tug-specific travel-mode burn rate (kg per kW·h);
           travel time is read from the precomputed time_matrix.

  Z_penalty = Σ_{s ∈ S} (1 − z_s)
       Number of tasks left unserved. The objective weights this by W
       (= penalty_weight, typically 10000) — so completing one more task
       beats burning W kg more fuel.

The two terms pull against each other: Z_penalty pushes toward serving MORE
tasks, but every served task contributes Z_service + Z_transit. A strong
heuristic picks the best subset of tasks given fuel + capacity + time-window
constraints.

────────────────────────────────────────────────────────────
Constraints
────────────────────────────────────────────────────────────

— Task service constraints
  (C1)  At most Γ_s tugboats serve task s (if served):
          Σ_{k∈K} y_sk ≤ Γ_s · z_s,   ∀s ∈ S
        i.e. |task_tugboats[s]| ≤ task_max_tugs[s-1].
  (C2)  Combined horsepower of serving tugs ≥ task's minimum requirement:
          Σ_{k∈K} y_sk · HP_k ≥ H_s^min · z_s,   ∀s ∈ S
        i.e. Σ_{k∈task_tugboats[s]} tugboat_horsepower[k] ≥ task_min_horsepower[s-1].

— Tugboat routing constraints
  (C3)  Each tugboat departs from its home base AT MOST ONCE:
          Σ_{s∈S} x_{b,s}^k ≤ 1,   ∀b ∈ B, k ∈ K_b
        Structurally guaranteed: routes[k] is a single ordered trip starting
        from tugboat k's home base.
  (C4)  Each tugboat returns to its home base AT MOST ONCE:
          Σ_{s∈S} x_{s,n-b}^k ≤ 1,   ∀b ∈ B, k ∈ K_b
        Structurally guaranteed: routes[k] ends at tugboat k's home base's
        destination node.
  (C5)  Flow conservation per tugboat per task:
          Σ_{i ∈ {b}∪S} x_{i,j}^k = Σ_{i ∈ S∪{n-b}} x_{j,i}^k,
                                            ∀j ∈ S, ∀b ∈ B, k ∈ K_b
        Equivalent here: if tug k visits task j, tug k must continue to
        exactly one next node. Enforced by routes[k] being a simple
        ordered list.
  (C6)  Linkage between routes and task_tugboats:
          y_sk = Σ_{i∈{b}∪S} x_{i,s}^k,   ∀s ∈ S, ∀b ∈ B, k ∈ K_b
        i.e. k ∈ task_tugboats[s] iff s appears in routes[k]. The set of
        tugs in task_tugboats[s] MUST equal the set of routes containing s.

— Base capacity constraints
  (C7)  At most δ_b tugboats depart from base b:
          Σ_{k∈K_b} Σ_{s∈S} x_{b,s}^k ≤ δ_b,   ∀b ∈ B
        i.e. # non-empty routes for tugs in K_b ≤ base_capacity[|b|-1].
  (C8)  At most δ_b tugboats return to base b (in this model, # departures
        equals # arrivals per base):
          Σ_{k∈K_b} Σ_{s∈S} x_{s,n-b}^k ≤ δ_b,   ∀b ∈ B
  (C9)  Tugboats cannot use non-home bases:
          x_{b,s}^k = 0 and x_{s,n-b}^k = 0 for k ∉ K_b
        Structurally guaranteed by the route construction.

— Time window constraints
  (C10) Task service start must fall within its time window:
          a_s · z_s ≤ τ_s ≤ b_s + M(1 − z_s),   ∀s ∈ S
        i.e. task_time_window_lower[s-1] ≤ task_start_times[s]
                                         ≤ task_time_window_upper[s-1] for executed s.
  (C11) Service must complete within the planning horizon:
          τ_s + T_s ≤ T_max + M(1 − z_s),   ∀s ∈ S
        i.e. task_start_times[s] + task_service_time[s-1] ≤ planning_horizon.

— Time propagation constraints (along each route)
  (C12) Tug k cannot start its first task before traveling from its home base:
          τ_j ≥ t_{b,j} − M(1 − x_{b,j}^k),   ∀j ∈ S, ∀b ∈ B, k ∈ K_b
        i.e. if routes[k] = [s₁, …], then task_start_times[s₁]
              ≥ time_matrix['{home_base_k}_{s₁}'].
  (C13) Tug k must finish task i and travel to task j before starting j:
          τ_j ≥ τ_i + T_i + t_{i,j} − M(1 − x_{i,j}^k),   ∀i,j ∈ S, ∀k ∈ K
        i.e. for consecutive (i, j) in routes[k],
          task_start_times[j] ≥ task_start_times[i] + task_service_time[i-1]
                                + time_matrix['{i}_{j}'].
        Also, after the last task task_L on tug k's route, the tug must
        return to its home base's destination node before T_max:
          task_start_times[task_L] + task_service_time[task_L - 1]
              + time_matrix['{task_L}_{n - home_base_k}']  ≤  planning_horizon.

— Fuel capacity constraint
  (C14) Total fuel each tugboat burns ≤ its fuel capacity:
        For each tugboat k with non-empty route, the sum of:
          • service fuel α_k · HP_k · Σ_{s∈routes[k]} T_s
          • out fuel β_k · HP_k · t_{home_base_k, first_task}
          • mid fuel β_k · HP_k · Σ_{(i,j) consecutive} t_{i,j}
          • in fuel β_k · HP_k · t_{last_task, n − home_base_k}
        must not exceed tugboat_fuel_capacity[k].

(C16/C17 from the original model — domain declarations of the binary x/y/z
and non-negativity of τ — are automatically satisfied when (C1)–(C14) and
the solution-dict type contract are respected, so they do not appear as
separate checks.)

────────────────────────────────────────────────────────────
Notes
────────────────────────────────────────────────────────────
• The "do-nothing" solution (every task unserved) is FEASIBLE and yields
  Z = W · n. Any candidate worth submitting should beat it. A strong
  heuristic decides for each task whether a feasible (route position,
  start time, collaborating tugs) is cheaper than the W skip cost.

• Coordination is implicit: τ_s is a single number, so any collaborating
  tug k ∈ task_tugboats[s] must arrive at task s by time τ_s and stay
  through τ_s + T_s. C9/C10 (same-start) are not separate checks because
  τ_s is a shared variable.

• Tooling: the `tools` dict (see "Available tools") provides `is_feasible`,
  `objective`, plus helpers for finding a feasible (route position, start
  time, collaborating tugs) triple for one task at a time. Use them rather
  than rewriting feasibility logic from scratch.
"""


def solve(**kwargs):
    """Solve a Multi-Base Tugboat Routing and Scheduling Problem (MTRSP-MB) instance.

    Args (keyword arguments — instance dict unpacked):

    ────── Dimensions ──────
        num_tasks    (int): n, number of tasks (1-indexed task ids 1..n).
        num_tugboats (int): m, number of tugboats (0-indexed tug ids 0..m-1).
        num_bases    (int): p, number of bases (base ids are -1..-p).

    ────── Per-task arrays (length n, indexed by task id s ∈ {1..n} via s-1) ──────
        task_max_tugs           (list[int]):   Γ_s — max tugboats per task.
        task_min_horsepower     (list[float]): H_s^min — minimum HP sum required.
        task_time_window_lower  (list[float]): a_s — earliest service start (hours).
        task_time_window_upper  (list[float]): b_s — latest service start (hours).
        task_service_time       (list[float]): T_s — fixed service duration (hours).

    ────── Per-tugboat arrays (length m, indexed by tug k ∈ [0, m)) ──────
        tugboat_horsepower      (list[float]): HP_k — tug horsepower (kW).
        tugboat_fuel_capacity   (list[float]): F_k^max — fuel tank capacity (kg).
        tugboat_alpha           (list[float]): α_k — service burn rate (kg/(kW·h)).
        tugboat_beta            (list[float]): β_k — travel burn rate (kg/(kW·h)).
        tugboat_base_assignment (list[int]):   home base of tug k (negative int, -1..-p).

    ────── Per-base arrays (length p, indexed by base index |b|-1) ──────
        base_capacity (list[int]): δ_b — max tugs that base b can dispatch / receive.

    ────── Network & system parameters ──────
        time_matrix       (dict[str, float]): sparse travel time matrix (hours).
            Keys are STRINGS of the form '<i>_<j>' where:
              • '<b>_<s>'         base origin b ∈ {-1..-p} → task s ∈ {1..n}
              • '<i>_<j>'         task i → task j  (i, j ∈ {1..n}, i ≠ j)
              • '<s>_<n+|b|>'     task s → base destination node n+|b| ∈ {n+1..n+p}
            Use these keys verbatim in your start-time + fuel calculations.
        big_M             (float): large constant for the original MILP (unused at run time).
        planning_horizon  (float): T_max — total horizon in hours (typically 24).
        penalty_weight    (float): W — penalty per unserved task (typically 10000).

    Returns:
        dict with EXACTLY these 3 keys:

          'routes' (list[list[int]]): length-m list. routes[k] is the
              ordered list of task ids (∈ {1..n}) that tugboat k serves.
              [] means tug k is unused. The implicit full route is
              [home_base_k, *routes[k], n - home_base_k] but ONLY the task
              ids are stored.

          'task_tugboats' (dict[int, list[int]]): for each served task s,
              the list of tugboat ids serving it. Keys are task ids ∈ {1..n};
              values are lists of tug ids ∈ {0..m-1}. Must be CONSISTENT with
              routes (C6): k ∈ task_tugboats[s]  iff  s ∈ routes[k].
              Only includes executed (z_s = 1) tasks — unserved tasks are
              absent from the dict.

          'task_start_times' (dict[int, float]): for each served task s,
              its start time τ_s (hours). Keys must equal task_tugboats.keys().
              All tugs in task_tugboats[s] are implicitly synchronized to
              start at this time.

    Example (n=4 tasks, m=3 tugs, p=2 bases; serves tasks 1,3 with collab):
        {
          'routes': [
              [1, 3],          # tugboat 0 (base -1): -1 → task 1 → task 3 → dest 5
              [3],             # tugboat 1 (base -1): -1 → task 3       → dest 5
              [],              # tugboat 2 (base -2): unused
          ],
          'task_tugboats':    {1: [0],    3: [0, 1]},
          'task_start_times': {1: 1.5,    3: 5.0},
        }
        Tasks 2 and 4 are unserved (z_2 = z_4 = 0), each paying W penalty.

    The "do nothing" return below is FEASIBLE — it just pays maximum
    penalty W·n. A strong solver serves as many tasks as it can while
    respecting all 14 constraints (see eval_func source for the exact check).
    """
    m = kwargs["num_tugboats"]
    return {
        "routes":           [[] for _ in range(m)],
        "task_tugboats":    {},
        "task_start_times": {},
    }


def load_data(file_path):
    """Parse one MTRSP-MB instance text file.

    Returns a list of instance dicts. MTRSP-MB stores ONE instance per
    file, so the returned list always has length 1.
    """
    inst = {}
    with open(file_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, val = line.split("=", 1)
            inst[key.strip()] = ast.literal_eval(val.strip())
    return [inst]


# ============================================================================
# eval_func — Source shown verbatim to the LLM in the feasibility prompt section.
# Every `raise Exception` is a constraint a solution must NOT trip.
# ============================================================================

def eval_func(
    # --- Dimensions ---
    num_tasks, num_tugboats, num_bases,
    # --- Per-task arrays (length n) ---
    task_max_tugs, task_min_horsepower,
    task_time_window_lower, task_time_window_upper, task_service_time,
    # --- Per-tugboat arrays (length m) ---
    tugboat_horsepower, tugboat_fuel_capacity,
    tugboat_alpha, tugboat_beta, tugboat_base_assignment,
    # --- Per-base array (length p) ---
    base_capacity,
    # --- Network ---
    time_matrix,
    # --- Scalars ---
    big_M, planning_horizon, penalty_weight,
    # --- Solution keys ---
    routes, task_tugboats, task_start_times,
):
    """Evaluate an MTRSP-MB solution.

    Raises Exception (with a descriptive message tagged (Cn) when applicable)
    if any of the 14 active constraints is violated. Otherwise returns the
    float objective Z = Z_fuel + W · Z_penalty (LOWER IS BETTER).
    """
    n = num_tasks
    m = num_tugboats
    p = num_bases
    T_max = planning_horizon
    W = penalty_weight

    # ─── Top-level shape ───────────────────────────────────────────────────
    if not isinstance(routes, list) or len(routes) != m:
        raise Exception(
            f"routes must be a list of length num_tugboats={m}, "
            f"got type={type(routes).__name__} len={len(routes) if hasattr(routes, '__len__') else '?'}")
    if not isinstance(task_tugboats, dict):
        raise Exception(
            f"task_tugboats must be a dict, got type={type(task_tugboats).__name__}")
    if not isinstance(task_start_times, dict):
        raise Exception(
            f"task_start_times must be a dict, got type={type(task_start_times).__name__}")

    # ─── Validate routes shape + per-task appearance ──────────────────────
    for k in range(m):
        route = routes[k]
        if not isinstance(route, list):
            raise Exception(
                f"routes[{k}] must be a list of task ids, got type={type(route).__name__}")
        seen_in_route = set()
        for task_id in route:
            if not isinstance(task_id, int):
                raise Exception(
                    f"routes[{k}] contains non-int task id {task_id!r} (type {type(task_id).__name__})")
            if not (1 <= task_id <= n):
                raise Exception(
                    f"routes[{k}] contains task_id={task_id} outside [1, {n}]")
            if task_id in seen_in_route:
                raise Exception(
                    f"routes[{k}] visits task {task_id} more than once (each route is simple)")
            seen_in_route.add(task_id)

    # ─── Derive executed set from routes; (C6) link to task_tugboats ──────
    executed = set()
    derived_tugs = {}  # task_id -> set of tug ids appearing in routes
    for k in range(m):
        for task_id in routes[k]:
            executed.add(task_id)
            derived_tugs.setdefault(task_id, set()).add(k)

    # (C6) task_tugboats keys must exactly equal `executed`
    tt_keys = set(task_tugboats.keys())
    if tt_keys != executed:
        raise Exception(
            f"task_tugboats keys {sorted(tt_keys)} must equal the set of tasks "
            f"appearing in routes {sorted(executed)} (C6)")

    # task_start_times keys must exactly equal `executed`
    ts_keys = set(task_start_times.keys())
    if ts_keys != executed:
        raise Exception(
            f"task_start_times keys {sorted(ts_keys)} must equal the set of "
            f"tasks appearing in routes {sorted(executed)}")

    # (C6) task_tugboats[s] must equal derived_tugs[s] as a set
    for s in executed:
        tugs_listed = task_tugboats[s]
        if not isinstance(tugs_listed, list):
            raise Exception(
                f"task_tugboats[{s}] must be a list of tug ids, got type={type(tugs_listed).__name__}")
        if len(set(tugs_listed)) != len(tugs_listed):
            raise Exception(
                f"task_tugboats[{s}]={tugs_listed} contains duplicate tug ids")
        for k_ in tugs_listed:
            if not isinstance(k_, int) or not (0 <= k_ < m):
                raise Exception(
                    f"task_tugboats[{s}] contains tug id {k_!r} not in [0, {m})")
        if set(tugs_listed) != derived_tugs[s]:
            raise Exception(
                f"task_tugboats[{s}]={sorted(set(tugs_listed))} disagrees with "
                f"routes-derived tugs {sorted(derived_tugs[s])} (C6)")

    # task_start_times values must be numeric
    for s in executed:
        ts = task_start_times[s]
        if not isinstance(ts, (int, float)) or isinstance(ts, bool):
            raise Exception(
                f"task_start_times[{s}]={ts!r} must be a numeric start time")
        if ts < 0:
            raise Exception(
                f"task_start_times[{s}]={ts} is negative (τ_s ≥ 0 required)")

    # ─── Per-task constraints (C1, C2, C10, C11) ──────────────────────────
    for s in executed:
        tugs = task_tugboats[s]
        # (C1) cardinality
        if len(tugs) > task_max_tugs[s - 1]:
            raise Exception(
                f"task {s} served by {len(tugs)} tugs > Γ_s={task_max_tugs[s-1]} (C1)")
        if len(tugs) < 1:
            raise Exception(
                f"task {s} is in routes/start_times but has 0 serving tugboats")
        # (C2) horsepower
        total_hp = sum(tugboat_horsepower[k_] for k_ in tugs)
        if total_hp < task_min_horsepower[s - 1]:
            raise Exception(
                f"task {s} total HP={total_hp} < H_s^min={task_min_horsepower[s-1]} (C2)")
        # (C10) time window
        ts = task_start_times[s]
        a_s = task_time_window_lower[s - 1]
        b_s = task_time_window_upper[s - 1]
        if ts < a_s - 1e-9 or ts > b_s + 1e-9:
            raise Exception(
                f"task {s} τ={ts} outside window [{a_s}, {b_s}] (C10)")
        # (C11) finish before T_max
        T_s = task_service_time[s - 1]
        if ts + T_s > T_max + 1e-9:
            raise Exception(
                f"task {s} τ+T_s={ts + T_s} > T_max={T_max} (C11)")

    # ─── Base capacity (C7, C8) ───────────────────────────────────────────
    base_depart_count = [0] * p   # 0-indexed by |b|-1
    for k in range(m):
        if len(routes[k]) == 0:
            continue
        b = tugboat_base_assignment[k]
        if not isinstance(b, int) or not (-p <= b <= -1):
            raise Exception(
                f"tugboat_base_assignment[{k}]={b} not in {{-1,...,-{p}}}")
        base_depart_count[-b - 1] += 1
    for b_idx in range(p):
        cap = base_capacity[b_idx]
        if base_depart_count[b_idx] > cap:
            raise Exception(
                f"base {-(b_idx+1)}: {base_depart_count[b_idx]} departures > δ_b={cap} (C7)")
        # C8 (arrivals) — # arrivals == # departures in this model
        if base_depart_count[b_idx] > cap:
            raise Exception(
                f"base {-(b_idx+1)}: {base_depart_count[b_idx]} arrivals > δ_b={cap} (C8)")

    # ─── Per-tugboat constraints (C12, C13, C14) ──────────────────────────
    # For each non-empty route: arrival at every task must be ≤ τ_s, the
    # return-to-base must finish by T_max, and fuel use ≤ capacity.
    EPS = 1e-7
    total_service_fuel = 0.0
    total_transit_fuel = 0.0
    for k in range(m):
        route = routes[k]
        if not route:
            continue
        home_base = tugboat_base_assignment[k]  # negative int
        dest_node = n - home_base               # positive int, > n
        HP_k = tugboat_horsepower[k]
        alpha_k = tugboat_alpha[k]
        beta_k = tugboat_beta[k]

        # (C12) From base origin to first task
        first_task = route[0]
        key_out = f"{home_base}_{first_task}"
        if key_out not in time_matrix:
            raise Exception(
                f"time_matrix missing key {key_out!r} (tug {k} departure)")
        t_out = time_matrix[key_out]
        arrival = t_out  # tug k can depart at time 0 from base
        if arrival > task_start_times[first_task] + EPS:
            raise Exception(
                f"tug {k}: arrival at first task {first_task} = {arrival} "
                f"> τ_{first_task}={task_start_times[first_task]} (C12)")

        # Accumulate fuel: out + first service
        tug_fuel = beta_k * HP_k * t_out
        tug_fuel += alpha_k * HP_k * task_service_time[first_task - 1]
        total_transit_fuel += beta_k * HP_k * t_out
        total_service_fuel += alpha_k * HP_k * task_service_time[first_task - 1]

        # (C13) Between consecutive tasks
        for u in range(len(route) - 1):
            i_task = route[u]
            j_task = route[u + 1]
            key_mid = f"{i_task}_{j_task}"
            if key_mid not in time_matrix:
                raise Exception(
                    f"time_matrix missing key {key_mid!r} (tug {k} mid)")
            t_mid = time_matrix[key_mid]
            # Earliest j start = end of i + travel
            arrival_j = task_start_times[i_task] + task_service_time[i_task - 1] + t_mid
            if arrival_j > task_start_times[j_task] + EPS:
                raise Exception(
                    f"tug {k}: arrival at task {j_task} = {arrival_j} > "
                    f"τ_{j_task}={task_start_times[j_task]} (after task {i_task}) (C13)")
            tug_fuel += beta_k * HP_k * t_mid
            tug_fuel += alpha_k * HP_k * task_service_time[j_task - 1]
            total_transit_fuel += beta_k * HP_k * t_mid
            total_service_fuel += alpha_k * HP_k * task_service_time[j_task - 1]

        # Return to base destination node — must finish by T_max
        last_task = route[-1]
        key_in = f"{last_task}_{dest_node}"
        if key_in not in time_matrix:
            raise Exception(
                f"time_matrix missing key {key_in!r} (tug {k} return)")
        t_in = time_matrix[key_in]
        return_finish = task_start_times[last_task] + task_service_time[last_task - 1] + t_in
        if return_finish > T_max + EPS:
            raise Exception(
                f"tug {k}: return finish={return_finish} > T_max={T_max} (C13/C11)")
        tug_fuel += beta_k * HP_k * t_in
        total_transit_fuel += beta_k * HP_k * t_in

        # (C14) fuel capacity
        if tug_fuel > tugboat_fuel_capacity[k] + EPS:
            raise Exception(
                f"tug {k}: fuel use {tug_fuel} > capacity {tugboat_fuel_capacity[k]} (C14)")

    # ─── Cost computation (all constraints passed) ────────────────────────
    z_penalty = n - len(executed)
    z_fuel = total_service_fuel + total_transit_fuel
    return float(z_fuel + W * z_penalty)
