"""Assemble drop-in contract files from a ContractContext. No LLM.

Native tools (no eval_func): config.py holds load_data + make_solution +
is_feasible + objective + a few helpers; spec.py (from the template) exposes
them via tools()."""
from __future__ import annotations
import importlib.util
from pathlib import Path

from .spec_template import render_spec

_HEADER = '"""Auto-generated by mace.contract (native tools, no eval_func)."""\n'


def _build_starter_code(ctx, slug: str) -> str:
    return (
        f'def solve(instance: dict, tools: dict, time_limit_s: float) -> dict:\n'
        f'    """Solve a {slug!r} instance under the ISTH interface.\n\n'
        f'    Input schema:\n{ctx.input_schema}\n\n'
        f'    Returns (solution dict):\n{ctx.output_schema}\n'
        f'    """\n'
        f'    raise NotImplementedError  # replace with your algorithm\n'
    )


def build_config_src(ctx) -> str:
    """config.py source: DESCRIPTION + load_data + make_solution + is_feasible +
    objective + helpers + HELPERS list + TOOLS_DESCRIPTION. Tolerant of fields
    not yet filled (used mid-pipeline to build a partial spec for validation)."""
    load_data_code = (ctx.load_data_code or "def load_data(path):\n    raise NotImplementedError").strip()
    parts = [_HEADER.rstrip("\n")]
    # The I draft usually already defines DESCRIPTION; only add one if it doesn't.
    if "DESCRIPTION" not in load_data_code:
        parts.append(f"DESCRIPTION = {repr(ctx.description or ctx.nl_description)}")
    parts += [
        load_data_code,
        (ctx.placeholder_solution_code or "def make_solution(instance):\n    return {}").strip(),
        (ctx.is_feasible_code or "def is_feasible(instance, solution):\n    return True, None").strip(),
        (ctx.objective_code or "def objective(instance, solution):\n    return 0.0").strip(),
        (ctx.helpers_code or "").strip(),
        f"HELPERS = {repr(ctx.helper_names or [])}",
        f"TOOLS_DESCRIPTION = {repr(ctx.tools_description or [])}",
    ]
    return "\n\n\n".join(p for p in parts if p)


def assemble_contract(ctx, slug: str, out_dir: str) -> str:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "config.py").write_text(build_config_src(ctx), encoding="utf-8")
    (out / "spec.py").write_text(
        render_spec(slug=slug, direction=ctx.direction,
                    starter_code=_build_starter_code(ctx, slug)),
        encoding="utf-8")
    (out / "__init__.py").write_text("", encoding="utf-8")
    return str(out)


def build_spec(ctx, slug: str, tmp_dir: str):
    """Assemble into tmp_dir and import the SPEC object — used mid-pipeline to
    validate T / helpers by running a real heuristic through the contract."""
    assemble_contract(ctx, slug, tmp_dir)
    spec_path = Path(tmp_dir) / "spec.py"
    s = importlib.util.spec_from_file_location(f"_ctr_spec_{slug}_{id(ctx)}", spec_path)
    mod = importlib.util.module_from_spec(s)
    s.loader.exec_module(mod)
    spec_obj = mod.SPEC
    # stash the underlying config module so callers can instrument tools (e.g.
    # the helper validator wraps a helper to confirm it is actually invoked).
    try:
        spec_obj._cfg_module = mod._cfg
    except Exception:
        pass
    return spec_obj
