"""Assemble drop-in contract files from a completed ContractContext. No LLM."""
from __future__ import annotations
from pathlib import Path

from .spec_template import render_spec

_CONFIG_HEADER = '"""Auto-generated by mace.contract. Authored I (load_data) + T (eval_func)."""\n'


def _build_starter_code(ctx, slug: str) -> str:
    return (
        f'def solve(instance: dict, tools: dict, time_limit_s: float) -> dict:\n'
        f'    """Solve a {slug!r} instance under the ISTH interface.\n\n'
        f'    Input schema:\n{ctx.input_schema}\n\n'
        f'    Returns:\n{ctx.output_schema}\n'
        f'    """\n'
        f'    # Trivial placeholder; replace with your algorithm.\n'
        f'    raise NotImplementedError\n'
    )


def _placeholder_solve(ctx) -> str:
    body = ctx.placeholder_solution_code or 'def make_solution(instance):\n    return {}'
    return (body + "\n\n"
            "def solve(**kwargs):\n"
            '    """Trivial feasible placeholder (the \'do nothing\' return)."""\n'
            "    return make_solution(kwargs)\n")


def assemble_contract(ctx, slug: str, out_dir: str) -> None:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    desc_literal = repr(ctx.description or ctx.nl_description)
    config_src = (
        _CONFIG_HEADER
        + f"DESCRIPTION = {desc_literal}\n\n\n"
        + (ctx.load_data_code or "") + "\n\n\n"
        + _placeholder_solve(ctx) + "\n\n\n"
        + (ctx.eval_func_code or "") + "\n"
    )
    (out / "config.py").write_text(config_src, encoding="utf-8")

    # feasibility_steps.py is an OPTIONAL prompt aid; spec.py imports it with a
    # graceful fallback to "". Only write it when one was generated.
    if ctx.feasibility_steps:
        (out / "feasibility_steps.py").write_text(
            '"""Auto-generated step-by-step feasibility narrative (prompt aid)."""\n'
            f"FEASIBILITY_STEPS_PY = r'''{ctx.feasibility_steps}'''\n", encoding="utf-8")

    if ctx.extras_code:
        (out / "extras.py").write_text(ctx.extras_code, encoding="utf-8")

    (out / "spec.py").write_text(
        render_spec(slug=slug, direction=ctx.direction,
                    starter_code=_build_starter_code(ctx, slug)),
        encoding="utf-8")

    (out / "__init__.py").write_text("", encoding="utf-8")
