"""Template for the per-problem spec.py of a NEWLY generated contract.

Native tools, no eval_func: spec.tools() exposes the directly-generated
is_feasible / objective (+ helpers) from config.py. Four tokens are filled by
str.replace (NOT str.format) so the literal { } braces in the body are safe.
  @@SLUG@@      -> importlib module suffix
  @@NAME@@      -> spec.name
  @@DIRECTION@@ -> repr(direction)
  @@STARTER@@   -> repr(starter_code)
"""
from __future__ import annotations

_TEMPLATE = '''\
"""ISTH spec for \'@@NAME@@\' (auto-generated by mace.contract; native tools, no eval_func)."""
from __future__ import annotations
import inspect
import math
import sys
import importlib.util
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
from mace.framework import ProblemSpec  # noqa: E402

_CONFIG_PATH = Path(__file__).resolve().parent / "config.py"
_ms = importlib.util.spec_from_file_location("_cfg_@@SLUG@@", _CONFIG_PATH)
_cfg = importlib.util.module_from_spec(_ms)
_ms.loader.exec_module(_cfg)

_DIRECTION = @@DIRECTION@@   # objective is authored lower-is-better

# Surface the is_feasible source to the heuristic generator so it can read
# every constraint boundary directly (the paper\'s step-by-step feasibility view).
try:
    _IS_FEAS_SRC = inspect.getsource(_cfg.is_feasible)
except Exception:
    _IS_FEAS_SRC = ""
_FEASIBILITY_DOC = (
    "CALLING CONVENTION: call `tools[\'is_feasible\'](solution) -> (bool, message)` "
    "and `tools[\'objective\'](solution) -> float`. The `instance` is ALREADY BOUND "
    "into these tools — do NOT pass it yourself. (Helper tools are likewise "
    "instance-bound: call `tools[\'name\'](...other args...)` without the instance.)\\n\\n"
    "A solution is feasible iff `tools[\'is_feasible\'](solution)` returns (True, None). "
    "The underlying source is shown below (it takes `instance` explicitly, but the tool "
    "wrapper binds it for you) so you can read every constraint boundary:\\n\\n"
    "```python\\n" + _IS_FEAS_SRC + "\\n```"
)

_HELPER_NAMES = list(getattr(_cfg, "HELPERS", []))


class _Spec(ProblemSpec):
    name = "@@NAME@@"
    description = _cfg.DESCRIPTION
    starter_code = @@STARTER@@
    feasibility_doc = _FEASIBILITY_DOC
    tools_description = list(getattr(_cfg, "TOOLS_DESCRIPTION", []))

    def load_data(self, path: str) -> dict:
        """Path may be \'file::idx\' to select one case from a multi-case file."""
        if "::" in path:
            actual, idx_str = path.rsplit("::", 1)
            idx = int(idx_str)
        else:
            actual, idx = path, 0
        result = _cfg.load_data(actual)
        if isinstance(result, list):
            if idx >= len(result):
                raise IndexError(f"case index {idx} >= {len(result)} cases in file")
            return result[idx]
        return result

    def tools(self, instance: dict) -> dict:
        inst = instance  # captured by closure

        def is_feasible(solution):
            try:
                ok, msg = _cfg.is_feasible(inst, solution)
            except Exception as e:
                return False, f"is_feasible raised: {type(e).__name__}: {e}"
            return (True, None) if ok else (False, msg or "infeasible")

        def objective(solution) -> float:
            try:
                val = float(_cfg.objective(inst, solution))
            except Exception:
                return 1e10
            if not math.isfinite(val):
                return 1e10
            return val

        out = {"is_feasible": is_feasible, "objective": objective}
        for _name in _HELPER_NAMES:
            _fn = getattr(_cfg, _name, None)
            if callable(_fn):
                out[_name] = (lambda *a, _f=_fn: _f(inst, *a))
        return out


SPEC = _Spec()
'''


def render_spec(slug: str, direction: str = "min", name: str | None = None,
                starter_code: str = "") -> str:
    """Fill the fixed native spec.py template. No LLM involved."""
    if name is None:
        name = slug
    out = _TEMPLATE
    out = out.replace("@@SLUG@@", slug)
    out = out.replace("@@NAME@@", name)
    out = out.replace("@@DIRECTION@@", repr(direction))
    out = out.replace("@@STARTER@@", repr(starter_code))
    return out
