"""CO-Bench-style config for the Multi-Tugboat Routing and Scheduling Problem (MTRSP).

This file is the single source of truth that the cobench spec builder consumes.

  - DESCRIPTION  → spec.description (LLM prompt: problem statement)
  - solve()      → spec.starter_code (LLM prompt: function signature + I/O schema)
  - load_data()  → spec.load_data (parses one .txt instance file → [instance_dict])
  - eval_func()  → spec.tools.is_feasible + spec.tools.objective (its SOURCE is
                   shown verbatim in the LLM prompt's feasibility section, so it
                   doubles as the constraint specification).

MTRSP is a hand-authored CO-Bench problem (no reference paper / known optima),
generated by problems/cobench/multi_tugboat_routing_and_scheduling_problem/build_instances.py.
The math model is mirrored from MACE's tugboat-scheduling source repository.
"""

import ast


DESCRIPTION = """\
Multi-Tugboat Routing and Scheduling Problem (MTRSP)

At a port operating over a planning horizon T^max (hours), n tasks
(berthing or unberthing operations) arrive, each with a time window, a
service duration, a minimum total horsepower, and a cap on how many
tugboats may serve it. K tugboats are available, each with horsepower,
fuel capacity, and per-kWh fuel-burn rates (one for service, one for
travel). Every tugboat starts and ends at a single depot.

A defining property: you may CHOOSE TO LEAVE A TASK UNEXECUTED. That is
a legal decision; it simply forfeits servicing that task at the cost of
a large per-task penalty (Z_penalty below). The decision space therefore
covers BOTH "which tasks to execute" AND "how to schedule the ones you
execute". Doing nothing (executing no task) is feasible — just expensive.

────────────────────────────────────────────────────────────
Decisions (for each task s ∈ {1..n} and each tugboat k ∈ {0..K-1})
────────────────────────────────────────────────────────────
Either leave task s unexecuted, OR commit to ALL of the following:
  • a non-empty set of tugboats {k₁, k₂, ...} ⊆ {0..K-1}, of size ≤ Γₛ,
    whose horsepower sum HP_{k₁} + ... ≥ Hₛᵐⁱⁿ
  • a single start time τₛ ∈ [aₛ, bₛ], shared by ALL serving tugs
  • for every serving tug, an ORDERING of the tasks it serves
    (a route): depot → task → ... → task → depot

The full solution is three coupled objects:
  routes[k]            — ordered list of task IDs (1-indexed) serviced by tug k
  task_tugboats[s]     — list of tugs serving task s (empty ⇒ z_s = 0)
  task_start_times[s]  — τₛ for task s (ignored when z_s = 0)

────────────────────────────────────────────────────────────
Objective:   minimize   Z = Z_fuel + W · Z_penalty
(LOWER IS BETTER)
────────────────────────────────────────────────────────────

  Z_fuel = Z_service + Z_transit

  Z_service = Σ_s Σ_{k ∈ task_tugboats[s]}  αₖ · HPₖ · Tₛ
       Fuel burned while serving tasks. αₖ is tug k's service burn-rate
       (kg per kW per hour); Tₛ is task s's service duration. Every
       tug assigned to task s pays its full αₖ · HPₖ · Tₛ.

  Z_transit = Σ_k Σ_{(i→j) in route k}  βₖ · HPₖ · t_{i,j}
       Fuel burned while moving between depot/tasks. βₖ is tug k's
       travel burn-rate; t_{i,j} is the travel time from node i's exit
       to node j's entrance. Includes depot → first task and last task
       → depot. A tug with empty route contributes 0.

  Z_penalty = Σ_s (1 − z_s) = number of unexecuted tasks

  W (penalty weight) is large (default 10000), so executing one more
  task dominates any reasonable fuel cost. A strong heuristic first
  maximizes executed tasks, then minimizes fuel.

────────────────────────────────────────────────────────────
Constraints (must hold whenever a task is executed)
────────────────────────────────────────────────────────────

— Task assignment & capability
  (C1)  Number of tugs serving task s is at most Γₛ.
        |task_tugboats[s]| ≤ Γₛ                       ∀ s ∈ executed.
  (C2)  Total horsepower of those tugs covers the requirement.
        Σ_{k ∈ task_tugboats[s]} HPₖ  ≥  Hₛᵐⁱⁿ        ∀ s ∈ executed.

— Routing structure (each tug visits depot once, services 0+ tasks, returns)
  (C3)  Every tug departs the depot AT MOST ONCE (route is a single
        sequence; empty if unused).
  (C4)  Every tug returns to the depot AT MOST ONCE (paired with C3).
  (C5)  Flow conservation: a task appears in routes[k] AT MOST ONCE per
        tug; the route is a simple sequence.
  (C6)  Linkage between routes and task_tugboats:
        s ∈ routes[k]  ⇔  k ∈ task_tugboats[s].
        Same start time τₛ for ALL serving tugs (collaborative tug
        synchronization — there is only one τₛ per task).

— Time windows (executed tasks only)
  (C7)  Task starts within its window.
        aₛ ≤ τₛ ≤ bₛ                                   ∀ s ∈ executed.
  (C8)  Task finishes within the planning horizon.
        τₛ + Tₛ ≤ T^max                                ∀ s ∈ executed.

— Time propagation (a tug must be ABLE to reach a task by its start time)
  (C9)  First task on a route: tug arrives from depot in time.
        τⱼ ≥ t_{0,j}                       for j = routes[k][0].
  (C10) Subsequent tasks: tug arrives from previous task's exit in time.
        τⱼ ≥ τᵢ + Tᵢ + t_{i,j}             for consecutive (i, j) in
                                            routes[k].
        (Note: (C9)/(C10) act per tug; if k serves task s, k must be
        physically able to reach s by τₛ in its own route.)

— Fuel capacity per tug
  (C11) Total fuel along k's route ≤ Fₖᵐᵃˣ.
        Σ_{s ∈ routes[k]} αₖ·HPₖ·Tₛ  +  Σ_{(i→j) in route k} βₖ·HPₖ·t_{i,j}
             ≤  Fₖᵐᵃˣ                                    ∀ k ∈ K.

────────────────────────────────────────────────────────────
Notes
────────────────────────────────────────────────────────────
• The "do-nothing" solution (every task unexecuted, every route empty)
  is feasible and yields Z = W · n. Any candidate worth submitting
  should beat it. A strong heuristic first packs tugboats with as many
  high-value tasks as their fuel + time budget allows, then prunes
  tasks that no remaining tug combo can feasibly serve.

• Indexing: tasks are 1..n in the math model and in the time_matrix
  keys (e.g., '0_3' = depot → task 3). The depot's outgoing index is 0
  and incoming index is n+1 (e.g., '5_11' = task 5 exit → depot when
  n=10). Per-task list parameters are stored 0-indexed: Tₛ for task s
  is at task_service_time[s-1]. Per-tug list parameters are also
  0-indexed: HPₖ for tug k is at tugboat_horsepower[k].

• Time matrix is sparse: time_matrix['i_j'] is the travel time (hours)
  from node i to node j. Only keys for legal moves are present:
    '0_j'      depot → task j entrance     j ∈ {1..n}
    'i_j'      task i exit → task j entrance  i, j ∈ {1..n}, i ≠ j
    'i_{n+1}'  task i exit → depot         i ∈ {1..n}

• Collaborative tasks (Γₛ > 1, Hₛᵐⁱⁿ exceeds any single tug's HP)
  REQUIRE multiple tugs synchronized at the same τₛ. (C6) bundles this
  synchronization with the routes/task_tugboats consistency invariant.

• Tooling: the `tools` dict provides `is_feasible`, `objective`, plus
  helpers for picking valid tug combinations, computing arrival times,
  and finding feasible (tug-set, start-time) pairs. Use them rather
  than rewriting feasibility logic from scratch.
"""


def solve(**kwargs):
    """Solve a Multi-Tugboat Routing and Scheduling Problem (MTRSP) instance.

    Args (keyword arguments — instance dict unpacked):

    ────── Dimensions ──────
        num_tasks    (int): n, number of tasks.
        num_tugboats (int): K, number of tugboats.

    ────── Per-task arrays (length n, indexed by task s ∈ {1..n} via [s-1]) ──────
        task_max_tugs           (list[int]):   Γₛ — max tugs allowed per task.
        task_min_horsepower     (list[float]): Hₛᵐⁱⁿ — min total horsepower (kW).
        task_time_window_lower  (list[float]): aₛ — earliest start time (h).
        task_time_window_upper  (list[float]): bₛ — latest start time (h).
        task_service_time       (list[float]): Tₛ — service duration (h).

    ────── Per-tugboat arrays (length K, indexed by tug k ∈ {0..K-1}) ──────
        tugboat_horsepower    (list[float]): HPₖ — horsepower (kW).
        tugboat_fuel_capacity (list[float]): Fₖᵐᵃˣ — fuel capacity (kg).
        tugboat_alpha         (list[float]): αₖ — service burn rate (kg per kW per h).
        tugboat_beta          (list[float]): βₖ — travel burn rate (kg per kW per h).

    ────── Travel ──────
        time_matrix (dict[str, float]): sparse, keys are strings:
            '0_j'      depot → task j entrance     j ∈ {1..n}
            'i_j'      task i exit → task j entrance  i, j ∈ {1..n}, i ≠ j
            'i_{n+1}'  task i exit → depot         i ∈ {1..n}
        Look up with f"{i}_{j}" using INTEGER node ids (0, 1..n, n+1).

    ────── System parameters ──────
        big_M            (float): large constant from MILP linearization (unused at runtime).
        planning_horizon (float): T^max — service must finish by this time (h).
        penalty_weight   (float): W — per-unexecuted-task penalty (default 10000).

    Returns:
        dict with EXACTLY these 3 keys:

        'routes' (list[list[int]]):
            length = num_tugboats. routes[k] is the ordered list of task ids
            (1-indexed, in service order) serviced by tug k.  Empty list ⇒
            tug k is unused.
            Example: [[1, 3, 5], [2, 4], []]

        'task_tugboats' (dict[int, list[int]]):
            keys MUST be exactly {1, 2, ..., n} (no missing keys).
            task_tugboats[s] is the list of tug ids (0-indexed) serving task s.
            Empty list ⇒ task s is unexecuted (z_s = 0).
            Example for n=5: {1: [0], 2: [1], 3: [0, 2], 4: [1], 5: []}

        'task_start_times' (dict[int, float]):
            keys MUST be exactly {1, 2, ..., n}.
            task_start_times[s] is τ_s (start time in hours) when task s is
            executed; IGNORED when task_tugboats[s] is empty (any nonnegative
            float, e.g., 0.0).
            Example: {1: 2.5, 2: 1.0, 3: 5.2, 4: 3.5, 5: 0.0}

        INVARIANT (C6): for every s ∈ {1..n} and every k ∈ {0..K-1}:
            s ∈ routes[k]  ⇔  k ∈ task_tugboats[s].

    The "do nothing" return below is FEASIBLE — every route is empty, every
    task is unexecuted, paying Z = W · n. A strong solver schedules as many
    tasks as possible while respecting all 11 constraints (see eval_func
    source for the exact check).
    """
    n = kwargs["num_tasks"]
    K = kwargs["num_tugboats"]
    return {
        "routes":           [[] for _ in range(K)],
        "task_tugboats":    {s: [] for s in range(1, n + 1)},
        "task_start_times": {s: 0.0 for s in range(1, n + 1)},
    }


def load_data(file_path):
    """Parse one MTRSP instance text file.

    Returns a list of instance dicts. MTRSP stores ONE instance per file, so
    the returned list always has length 1.
    """
    inst = {}
    with open(file_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, val = line.split("=", 1)
            inst[key.strip()] = ast.literal_eval(val.strip())
    return [inst]


# ============================================================================
# eval_func — Source shown verbatim to the LLM in the feasibility prompt
# section. Every `raise Exception` is a constraint a solution must NOT trip.
# ============================================================================

# Floating-point tolerance for time and fuel comparisons.
_TOL = 1e-6


def eval_func(
    # --- Dimensions ---
    num_tasks, num_tugboats,
    # --- Per-task arrays (length n) ---
    task_max_tugs, task_min_horsepower,
    task_time_window_lower, task_time_window_upper, task_service_time,
    # --- Per-tugboat arrays (length K) ---
    tugboat_horsepower, tugboat_fuel_capacity, tugboat_alpha, tugboat_beta,
    # --- Travel & scalars ---
    time_matrix, big_M, planning_horizon, penalty_weight,
    # --- Solution keys ---
    routes, task_tugboats, task_start_times,
):
    """Evaluate an MTRSP solution.

    Raises Exception (with a descriptive message tagged with the violated
    constraint code, e.g. "(C7)") if any of the 11 active constraints is
    violated. Otherwise returns the float objective
    Z = Z_fuel + W · Z_penalty  (LOWER IS BETTER).
    """
    n = num_tasks
    K = num_tugboats
    T_max = planning_horizon
    W = penalty_weight
    expected_task_keys = set(range(1, n + 1))

    # ─── Top-level shape ───────────────────────────────────────────────────
    if not isinstance(routes, list) or len(routes) != K:
        raise Exception(
            f"routes must be list of length num_tugboats={K}, got "
            f"type={type(routes).__name__} "
            f"len={len(routes) if hasattr(routes, '__len__') else 'n/a'}"
        )
    if not isinstance(task_tugboats, dict) or set(task_tugboats.keys()) != expected_task_keys:
        raise Exception(
            f"task_tugboats must be dict with keys exactly {{1..{n}}}, "
            f"got type={type(task_tugboats).__name__}"
        )
    if not isinstance(task_start_times, dict) or set(task_start_times.keys()) != expected_task_keys:
        raise Exception(
            f"task_start_times must be dict with keys exactly {{1..{n}}}, "
            f"got type={type(task_start_times).__name__}"
        )

    # ─── Validate routes data structure ───────────────────────────────────
    for k, route in enumerate(routes):
        if not isinstance(route, list):
            raise Exception(
                f"routes[{k}] must be list, got {type(route).__name__}")
        if len(route) != len(set(route)):
            # Duplicate task in a single tug's route violates C5
            # (flow conservation: each (s,k) pair has at most one entering arc).
            raise Exception(
                f"routes[{k}]={route} contains duplicate task id (C5)")
        for s in route:
            if not isinstance(s, int) or not (1 <= s <= n):
                raise Exception(
                    f"routes[{k}] entry {s!r} not an integer in [1, {n}]")

    # ─── Validate task_tugboats + consistency with routes (C6) ────────────
    for s in range(1, n + 1):
        tugs_for_s = task_tugboats[s]
        if not isinstance(tugs_for_s, list):
            raise Exception(
                f"task_tugboats[{s}] must be list, got "
                f"{type(tugs_for_s).__name__}")
        if len(tugs_for_s) != len(set(tugs_for_s)):
            raise Exception(
                f"task_tugboats[{s}]={tugs_for_s} has duplicate tug id")
        for k in tugs_for_s:
            if not isinstance(k, int) or not (0 <= k < K):
                raise Exception(
                    f"task_tugboats[{s}] entry {k!r} not in [0, {K})")
        # C6: every k claiming to serve s must have s in its route
        for k in tugs_for_s:
            if s not in routes[k]:
                raise Exception(
                    f"inconsistency: tug {k} in task_tugboats[{s}] but task "
                    f"{s} not in routes[{k}] (C6)")

    # C6 mirror: every (k, s) pair with s in route k must also be in task_tugboats[s]
    for k, route in enumerate(routes):
        for s in route:
            if k not in task_tugboats[s]:
                raise Exception(
                    f"inconsistency: task {s} in routes[{k}] but tug {k} not "
                    f"in task_tugboats[{s}] (C6)")

    # ─── Per-task constraints (executed tasks only) ───────────────────────
    executed = set()
    for s in range(1, n + 1):
        tugs_for_s = task_tugboats[s]
        if not tugs_for_s:
            continue  # unexecuted task — z_s = 0, no further checks
        executed.add(s)

        # (C1) at most Γ_s tugs per task
        if len(tugs_for_s) > task_max_tugs[s - 1]:
            raise Exception(
                f"task {s} has {len(tugs_for_s)} tugs > "
                f"task_max_tugs[{s-1}]={task_max_tugs[s - 1]} (C1)")

        # (C2) total HP ≥ Hₛᵐⁱⁿ
        total_hp = sum(tugboat_horsepower[k] for k in tugs_for_s)
        if total_hp < task_min_horsepower[s - 1] - _TOL:
            raise Exception(
                f"task {s} total HP={total_hp} < "
                f"task_min_horsepower[{s-1}]={task_min_horsepower[s - 1]} (C2)")

        # (C7) time window
        try:
            tau_s = float(task_start_times[s])
        except Exception:
            raise Exception(
                f"task_start_times[{s}]={task_start_times[s]!r} not a number")
        a_s = task_time_window_lower[s - 1]
        b_s = task_time_window_upper[s - 1]
        if tau_s < a_s - _TOL:
            raise Exception(
                f"task {s} start={tau_s} < window lower {a_s} (C7)")
        if tau_s > b_s + _TOL:
            raise Exception(
                f"task {s} start={tau_s} > window upper {b_s} (C7)")

        # (C8) finishes within planning horizon
        T_s = task_service_time[s - 1]
        if tau_s + T_s > T_max + _TOL:
            raise Exception(
                f"task {s} finish={tau_s + T_s} > planning_horizon={T_max} (C8)")

    # ─── Per-tug constraints: time propagation (C9/C10) + fuel (C11) ──────
    # Also accumulate Z_fuel during the same pass.
    z_fuel = 0.0
    for k, route in enumerate(routes):
        if not route:
            continue

        hp_k = tugboat_horsepower[k]
        alpha_k = tugboat_alpha[k]
        beta_k = tugboat_beta[k]
        f_max = tugboat_fuel_capacity[k]

        current_time = 0.0
        current_node = 0   # depot start
        tug_fuel = 0.0

        for idx, s in enumerate(route):
            T_s = task_service_time[s - 1]
            travel_key = f"{current_node}_{s}"
            if travel_key not in time_matrix:
                raise Exception(
                    f"time_matrix missing key {travel_key!r} needed for tug "
                    f"{k} route step {idx} (task {s})")
            t_travel = time_matrix[travel_key]

            # (C9 first step / C10 between tasks): arrival ≤ task start
            arrival = current_time + t_travel
            tau_s = float(task_start_times[s])
            if arrival > tau_s + _TOL:
                code = "C9" if idx == 0 else "C10"
                raise Exception(
                    f"tug {k} cannot reach task {s}: arrives at {arrival:.4f}, "
                    f"task starts at {tau_s:.4f} ({code})")

            tug_fuel += beta_k * hp_k * t_travel    # transit
            tug_fuel += alpha_k * hp_k * T_s        # service

            current_time = tau_s + T_s
            current_node = s

        # Return-to-depot leg
        end_depot = n + 1
        return_key = f"{current_node}_{end_depot}"
        if return_key not in time_matrix:
            raise Exception(
                f"time_matrix missing key {return_key!r} needed for tug "
                f"{k} return-to-depot leg")
        tug_fuel += beta_k * hp_k * time_matrix[return_key]

        # (C11) fuel capacity per tug
        if tug_fuel > f_max + _TOL:
            raise Exception(
                f"tug {k} total fuel {tug_fuel:.4f} > capacity {f_max} (C11)")

        z_fuel += tug_fuel

    # ─── Cost (Z = Z_fuel + W · Z_penalty) ────────────────────────────────
    z_penalty = float(n - len(executed))
    return float(z_fuel + W * z_penalty)
