"""CO-Bench-style config for the Multi-Tugboat Routing Problem with Variable Speed (MTRSP-VS).

This file is the single source of truth that the cobench spec builder consumes.

  - DESCRIPTION  → spec.description (LLM prompt: problem statement)
  - solve()      → spec.starter_code (LLM prompt: function signature + I/O schema)
  - load_data()  → spec.load_data (parses one .txt instance file → [instance_dict])
  - eval_func()  → spec.tools.is_feasible + spec.tools.objective (its SOURCE is
                   shown verbatim in the LLM prompt's feasibility section, so it
                   doubles as the constraint specification).

MTRSP-VS is a hand-authored CO-Bench problem (no reference paper / known optima),
generated by problems/cobench/multi_tugboat_routing_problem_with_variable_speed/
build_instances.py. Adapted from the MACE-source mtrsp_vs problem.
"""

import ast


DESCRIPTION = """\
Multi-Tugboat Routing Problem with Variable Speed (MTRSP-VS)

A harbor has m tugboats stationed at a common depot and n service tasks
scattered across the port. Every task s has a fixed location and a time
window [aₛ, bₛ] during which service may BEGIN. Each task is a stretch of
length dₛ (nautical miles) along which a vessel must be towed; while the
tug performs the service it moves at a chosen speed.

Each task has TWO end-points (entrance and exit). A tug that completes a
task ends at the task's exit location and may then transit to the next
task's entrance — pairwise distances task_to_task_distance[i][j] capture
exit-of-i → entrance-of-j. Routes start at the depot and end at the depot.

A defining property: you may CHOOSE TO LEAVE SOME TASKS UNEXECUTED.
That is a legal decision; it simply forfeits servicing that task at the
cost of a large per-task penalty (penalty_weight W below). The decision
space therefore covers BOTH "which tasks to execute" AND "how to schedule
the executed ones". Doing nothing is feasible — just expensive.

────────────────────────────────────────────────────────────
Decisions (continuous-time, 0-indexed tasks 0..n-1 and tugs 0..m-1)
────────────────────────────────────────────────────────────
For each task s, EITHER leave it unexecuted, OR commit to ALL of:
  • Assign 1..Γₛ tugboats (collaborative if > 1, total HP must meet H^min_s)
  • A single service start time τₛ ∈ [aₛ, bₛ]
  • A service speed level ℓ ∈ {0,1,2} ↔ {slow 6kn, medium 10kn, fast 15kn}

For each tug k:
  • A route routes[k] = ordered list of task IDs the tug visits
  • A transit speed level for EACH arc in the route, including
    depot→first task and last task→depot
  • Tug must arrive at every task in its route by the task's start time
  • Tug's total fuel (service + transit) must not exceed F^max_k

Speed indices ℓ map to physical speed vₗ:
    ℓ=0 (slow)   v₀ = 6  kn
    ℓ=1 (medium) v₁ = 10 kn
    ℓ=2 (fast)   v₂ = 15 kn

Service time at speed ℓ for task s: Tₛ^ℓ = dₛ / vₗ
Transit time at speed ℓ on arc (i→j): tᵢⱼ^ℓ = dᵢⱼ / vₗ

────────────────────────────────────────────────────────────
Objective:   minimize   Z = service_fuel + transit_fuel + W · (#unexecuted)
(LOWER IS BETTER)
────────────────────────────────────────────────────────────

  Service fuel: Σₛ_executed Σ_{k serving s} ψₛₖₗ(s)
    where ψₛₖₗ = αₖ · HPₖ · dₛ · (vₗ² / v_medium³)    [kg]
    αₖ is tug k's service fuel coefficient (kg / kW / h),
    HPₖ is tug k's horsepower (kW),
    vₗ is the service speed chosen for task s,
    v_medium = 10 kn is the reference speed (so ψ scales like vₗ²).

  Transit fuel: Σₖ Σ_{arcs in route k} φᵢⱼₖₗ
    where φᵢⱼₖₗ = βₖ · HPₖ · dᵢⱼ · (vₗ² / v_medium³)    [kg]
    βₖ is tug k's transit fuel coefficient (typically βₖ < αₖ).

  Penalty: W · |unexecuted tasks|
    W ≈ 1e5 — dropping a task is much more costly than fuel for a
    typical execution, so the heuristic should serve as many tasks as
    physically feasible.

────────────────────────────────────────────────────────────
Constraints (must hold whenever a task is executed)
────────────────────────────────────────────────────────────

— Task assignment & capability
  (C1)  At most Γₛ tugboats may serve task s.
        |{k : s ∈ routes[k]}| ≤ task_max_tugs[s].
  (C2)  Total horsepower of tugs serving s ≥ s's minimum requirement.
        Σ_{k serving s} HPₖ ≥ task_min_horsepower[s].

— Routing structure (implicit in `routes`)
  (C3)  Each tug leaves the depot at most once  (route is a single sequence).
  (C4)  Each tug returns to the depot at most once.
  (C5)  Flow conservation within a tug's route (consecutive tasks chained).
  (C6)  yₛₖ = 1 iff s ∈ routes[k]  (link between assignment and route).

— Speed selection (one speed per arc / task, ℓ ∈ {0,1,2})
  (C7)  Exactly one transit speed per arc in every route.
        len(transit_speeds[k]) == len(routes[k]) + 1, each ∈ {0,1,2}.
  (C8)  Exactly one service speed per executed task.
        service_speeds[s] ∈ {0,1,2} for every s in some route.

— Time windows
  (C9)  aₛ ≤ τₛ ≤ bₛ.
  (C10) τₛ + dₛ / v_{service_speeds[s]} ≤ T^max   (planning_horizon).

— Time propagation along each tug's route
  (C11) For tug k, depot → first task arrival is on time:
        d_{0,s₀} / v_{transit_speeds[k][0]} ≤ τ_{s₀}.
  (C12) For consecutive tasks s_i, s_{i+1} on tug k's route:
        τ_{s_i} + d_{s_i}/v_{service_speeds[s_i]}
              + d_{s_i, s_{i+1}}/v_{transit_speeds[k][i+1]}
              ≤ τ_{s_{i+1}}.
        (Collaborative service: all tugs serving s arrive by τₛ; they may
        wait — waiting is free, only travel burns fuel.)

— Fuel capacity per tug
  (C13) For each tug k, total fuel (service + transit, summed over k's
        visited tasks and arcs) ≤ tugboat_fuel_capacity[k] (F^max_k).

────────────────────────────────────────────────────────────
Solution shape (what `solve` MUST return)
────────────────────────────────────────────────────────────
A dict with EXACTLY these 4 keys:

  'routes' (dict[int, list[int]]):
        Tugboat-id (0..m-1) → ordered list of task-ids (0-indexed) it visits.
        STRICT: all m tug IDs must be present. Empty list = unused tug.
        A task may appear in MULTIPLE routes (collaborative service);
        within a single route it may NOT appear twice.

  'service_speeds' (dict[int, int]):
        Task-id → speed level {0,1,2}. ONLY executed tasks appear as keys.

  'start_times' (dict[int, float]):
        Task-id → service start time τₛ (continuous, hours).
        ONLY executed tasks appear as keys.
        For multi-tug tasks: ALL serving tugs MUST arrive by τₛ.

  'transit_speeds' (dict[int, list[int]]):
        Tugboat-id (0..m-1) → list of speed levels for each arc in the
        tug's route. STRICT: all m tug IDs must be present.
        Length: exactly len(routes[k]) + 1.
        Arc 0  = depot → first task entrance.
        Arc i  = task[i-1] exit → task[i] entrance, for 1 ≤ i ≤ |route|-1.
        Last arc = last task exit → depot.
        If routes[k] is empty, transit_speeds[k] must be [].

────────────────────────────────────────────────────────────
Notes
────────────────────────────────────────────────────────────
• The "do-nothing" solution (every task unexecuted, every tug idle) is
  feasible and yields Z = W · n. Any candidate worth submitting should
  beat it. A strong heuristic decides for each task whether the
  achievable fuel cost is cheaper than W; if so, it constructs a feasible
  triple (tug subset, speed, schedule) respecting all 13 constraints.

• Tooling: the `tools` dict (see "Available tools") provides
  `is_feasible`, `objective`, plus helpers — speed-cost queries, a
  feasible-tug-combo finder, and a feasible-assignment finder. Use them
  rather than rewriting feasibility logic from scratch.
"""


def solve(**kwargs):
    """Solve a Multi-Tugboat Routing Problem with Variable Speed (MTRSP-VS) instance.

    Args (keyword arguments — instance dict unpacked):

    ────── Dimensions ──────
        num_tasks         (int):  n, number of tasks.
        num_tugboats      (int):  m, number of tugboats.
        num_speed_levels  (int):  3 (slow / medium / fast — fixed).

    ────── Per-task arrays (length n, indexed by s ∈ [0, n)) ──────
        task_max_tugs           (list[int]):   Γₛ — max concurrent tugs.
        task_min_horsepower     (list[float]): H^min_s — required HP sum.
        task_time_window_lower  (list[float]): aₛ — earliest service start (h).
        task_time_window_upper  (list[float]): bₛ — latest service start (h).
        task_service_distance   (list[float]): dₛ — service length (n.m.).

    ────── Per-tug arrays (length m, indexed by k ∈ [0, m)) ──────
        tugboat_horsepower     (list[float]): HPₖ — engine power (kW).
        tugboat_fuel_capacity  (list[float]): F^max_k — fuel tank (kg).
        tugboat_alpha          (list[float]): αₖ — service fuel coef (kg/kW/h).
        tugboat_beta           (list[float]): βₖ — transit fuel coef (kg/kW/h).

    ────── Speed levels ──────
        speed_level_names         (list[str]):   ['slow', 'medium', 'fast'].
        speed_values              (list[float]): [6.0, 10.0, 15.0]  (kn).
        speed_power_coefficients  (list[float]): [0.216, 1.0, 3.375] (ρₗ = (vₗ/v_medium)³).

    ────── Distances (all in nautical miles) ──────
        depot_to_task_distance  (list[float]):       length n, d(depot → entrance of task j).
        task_to_depot_distance  (list[float]):       length n, d(exit of task i → depot).
        task_to_task_distance   (list[list[float]]): n×n, [i][j] = d(exit i → entrance j).
                                                     [i][i] = 0.0 (never used).

    ────── System parameters ──────
        big_M             (float): 1000.0 — Big-M for linearization (informational).
        planning_horizon  (float): T^max — total operations horizon (hours, typically 24).
        penalty_weight    (float): W — per-unexecuted-task penalty (typically 1e5).

    Returns:
        dict with EXACTLY these 4 keys.

        'routes' (dict[int, list[int]]):
            Tug-id (0..m-1, ALL present) → list of task-ids (0-indexed) in
            visit order. Empty list = unused tug. A task may appear in
            MULTIPLE tugs' routes (collaborative service).

        'service_speeds' (dict[int, int]):
            Task-id → speed level ∈ {0, 1, 2}. Only executed tasks.

        'start_times' (dict[int, float]):
            Task-id → service start time τₛ (hours, ≥ 0). Only executed tasks.

        'transit_speeds' (dict[int, list[int]]):
            Tug-id (0..m-1, ALL present) → list of speed levels for each arc.
            Length = len(routes[k]) + 1. Arc 0 = depot→first;
            arc i = tasks[i-1]→tasks[i]; last = lastTask→depot.

    Example (n=4 tasks, m=2 tugs; tug 0 solo-serves task 3 then collab-serves
    task 1 with tug 1; task 0 unexecuted):
        {
          'routes':         {0: [3, 1], 1: [1]},
          'service_speeds': {3: 1, 1: 0},
          'start_times':    {3: 0.5, 1: 4.2},
          'transit_speeds': {0: [1, 2, 1], 1: [1, 1]},
        }

    The "do nothing" return below is FEASIBLE — it pays maximum penalty
    W · n. A strong solver executes as many tasks as physically feasible
    while keeping total fuel below capacity.
    """
    m = kwargs["num_tugboats"]
    return {
        "routes":         {k: []  for k in range(m)},
        "service_speeds": {},
        "start_times":    {},
        "transit_speeds": {k: []  for k in range(m)},
    }


def load_data(file_path):
    """Parse one MTRSP-VS instance text file.

    Returns a list of instance dicts. MTRSP-VS stores ONE instance per file,
    so the returned list always has length 1. (CO-Bench convention permits
    multiple instances per file; MTRSP-VS doesn't use that.)
    """
    inst = {}
    with open(file_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, val = line.split("=", 1)
            inst[key.strip()] = ast.literal_eval(val.strip())
    return [inst]


# ============================================================================
# eval_func — Source shown verbatim to the LLM in the feasibility prompt section.
# Every `raise Exception` is a constraint a solution must NOT trip.
# ============================================================================

def eval_func(
    # --- Dimensions ---
    num_tasks, num_tugboats, num_speed_levels,
    # --- Per-task arrays (length n) ---
    task_max_tugs, task_min_horsepower,
    task_time_window_lower, task_time_window_upper, task_service_distance,
    # --- Per-tug arrays (length m) ---
    tugboat_horsepower, tugboat_fuel_capacity, tugboat_alpha, tugboat_beta,
    # --- Speed levels ---
    speed_level_names, speed_values, speed_power_coefficients,
    # --- Distances ---
    depot_to_task_distance, task_to_depot_distance, task_to_task_distance,
    # --- System parameters ---
    big_M, planning_horizon, penalty_weight,
    # --- Solution keys ---
    routes, service_speeds, start_times, transit_speeds,
):
    """Evaluate an MTRSP-VS solution.

    Raises Exception (with descriptive message tagged with the constraint
    code) if any of the 13 active constraints is violated. Otherwise returns
    the float objective  Z = service_fuel + transit_fuel + W·(#unexecuted)
    (LOWER IS BETTER).
    """
    n = num_tasks
    m = num_tugboats
    T_max = planning_horizon
    W = penalty_weight
    v_medium = speed_values[1]
    # Numerical tolerance for time/fuel inequalities — instances are float-valued.
    EPS = 1e-6

    # ─── Top-level shape ───────────────────────────────────────────────────
    if not isinstance(routes, dict):
        raise Exception(f"routes must be dict, got type={type(routes).__name__}")
    if not isinstance(transit_speeds, dict):
        raise Exception(f"transit_speeds must be dict, got type={type(transit_speeds).__name__}")
    if not isinstance(service_speeds, dict):
        raise Exception(f"service_speeds must be dict, got type={type(service_speeds).__name__}")
    if not isinstance(start_times, dict):
        raise Exception(f"start_times must be dict, got type={type(start_times).__name__}")

    expected_tug_keys = set(range(m))
    if set(routes.keys()) != expected_tug_keys:
        raise Exception(
            f"routes must have keys exactly {{0..{m-1}}}, got {sorted(routes.keys())}")
    if set(transit_speeds.keys()) != expected_tug_keys:
        raise Exception(
            f"transit_speeds must have keys exactly {{0..{m-1}}}, got {sorted(transit_speeds.keys())}")

    # ─── Per-tug route + transit_speeds shape ──────────────────────────────
    for k in range(m):
        route = routes[k]
        speeds_k = transit_speeds[k]
        if not isinstance(route, list):
            raise Exception(f"routes[{k}] must be list, got {type(route).__name__}")
        if not isinstance(speeds_k, list):
            raise Exception(f"transit_speeds[{k}] must be list, got {type(speeds_k).__name__}")

        # Within-route uniqueness: a tug doesn't visit the same task twice.
        if len(set(route)) != len(route):
            raise Exception(f"tug {k} route has duplicate tasks: {route}")
        # Every entry is a valid task id.
        for s in route:
            if not isinstance(s, int) or not (0 <= s < n):
                raise Exception(f"tug {k} route contains invalid task id {s!r} (must be int in [0, {n}))")

        # (C7) transit_speeds[k] length: 0 when route is empty, else len(route)+1.
        # Each level ∈ {0,1,2}.
        expected_arcs = (len(route) + 1) if route else 0
        if len(speeds_k) != expected_arcs:
            raise Exception(
                f"tug {k} transit_speeds length {len(speeds_k)} != expected {expected_arcs} "
                f"(len(routes[{k}])+1 if route else 0) (C7)")
        for arc_idx, lvl in enumerate(speeds_k):
            if not isinstance(lvl, int) or not (0 <= lvl < num_speed_levels):
                raise Exception(
                    f"tug {k} arc {arc_idx} transit speed level {lvl!r} not in "
                    f"{{0..{num_speed_levels-1}}} (C7)")

    # ─── Derive executed_tasks + task_tugboats ─────────────────────────────
    executed_tasks = set()
    task_tugboats = {}     # task_id → list[tug_id], in route-encounter order
    for k in range(m):
        for s in routes[k]:
            executed_tasks.add(s)
            task_tugboats.setdefault(s, []).append(k)

    # service_speeds + start_times keys must equal executed_tasks exactly.
    if set(service_speeds.keys()) != executed_tasks:
        raise Exception(
            f"service_speeds keys {sorted(service_speeds.keys())} must equal executed "
            f"tasks {sorted(executed_tasks)} (C8)")
    if set(start_times.keys()) != executed_tasks:
        raise Exception(
            f"start_times keys {sorted(start_times.keys())} must equal executed "
            f"tasks {sorted(executed_tasks)} (C9)")

    # ─── Per-task constraint checks ────────────────────────────────────────
    service_time = {}     # task_id → d_s / v_{service_speed} (cached)
    for s in executed_tasks:
        # (C8) service speed valid level
        lvl_s = service_speeds[s]
        if not isinstance(lvl_s, int) or not (0 <= lvl_s < num_speed_levels):
            raise Exception(
                f"service_speeds[{s}] = {lvl_s!r} not in {{0..{num_speed_levels-1}}} (C8)")

        # (C1) tug count limit
        tugs_s = task_tugboats[s]
        if len(tugs_s) > task_max_tugs[s]:
            raise Exception(
                f"task {s} served by {len(tugs_s)} tugs > task_max_tugs[{s}]={task_max_tugs[s]} (C1)")
        if len(tugs_s) < 1:
            # Shouldn't happen given derivation, but defensive.
            raise Exception(f"task {s} in executed_tasks but no tug serves it")

        # (C2) horsepower sum ≥ min requirement
        hp_sum = sum(tugboat_horsepower[k] for k in tugs_s)
        if hp_sum < task_min_horsepower[s] - EPS:
            raise Exception(
                f"task {s} HP sum {hp_sum} < required {task_min_horsepower[s]} (C2)")

        # (C9) time window: a_s ≤ τ_s ≤ b_s
        tau_s = start_times[s]
        if not isinstance(tau_s, (int, float)):
            raise Exception(f"start_times[{s}] = {tau_s!r} not numeric (C9)")
        if tau_s < task_time_window_lower[s] - EPS or tau_s > task_time_window_upper[s] + EPS:
            raise Exception(
                f"task {s} start_time {tau_s} outside window "
                f"[{task_time_window_lower[s]}, {task_time_window_upper[s]}] (C9)")

        # (C10) τ_s + service_time ≤ T_max
        d_s = task_service_distance[s]
        v_ls = speed_values[lvl_s]
        T_s = d_s / v_ls
        service_time[s] = T_s
        if tau_s + T_s > T_max + EPS:
            raise Exception(
                f"task {s} finish time {tau_s + T_s} > planning_horizon {T_max} (C10)")

    # ─── Time propagation along each tug's route (C11, C12) ────────────────
    for k in range(m):
        route = routes[k]
        if not route:
            continue
        speeds_k = transit_speeds[k]

        # (C11) depot → first task
        s0 = route[0]
        d0 = depot_to_task_distance[s0]
        v0 = speed_values[speeds_k[0]]
        arrival = d0 / v0
        if arrival > start_times[s0] + EPS:
            raise Exception(
                f"tug {k} arrives at task {s0} at {arrival} > start_time {start_times[s0]} (C11)")

        # (C12) between consecutive tasks
        for i in range(1, len(route)):
            si_prev = route[i - 1]
            si = route[i]
            end_prev = start_times[si_prev] + service_time[si_prev]
            d_ij = task_to_task_distance[si_prev][si]
            v_ij = speed_values[speeds_k[i]]
            arrival = end_prev + d_ij / v_ij
            if arrival > start_times[si] + EPS:
                raise Exception(
                    f"tug {k} arc {si_prev}->{si}: arrival {arrival} > start_time "
                    f"{start_times[si]} (C12)")

        # No constraint on the depot return time (within T_max not required by
        # the math model — only τ_s + T_s ≤ T_max for the LAST task is C10,
        # already checked above). But we still verify the return arc speed
        # exists (handled by the length check in C7 above).

    # ─── (C13) per-tug fuel capacity ───────────────────────────────────────
    tug_fuel = [0.0] * m
    for k in range(m):
        route = routes[k]
        if not route:
            continue
        speeds_k = transit_speeds[k]
        HP_k = tugboat_horsepower[k]
        alpha_k = tugboat_alpha[k]
        beta_k = tugboat_beta[k]

        # Service fuel for every task this tug serves
        for s in route:
            d_s = task_service_distance[s]
            v_ls = speed_values[service_speeds[s]]
            psi = alpha_k * HP_k * d_s * (v_ls ** 2) / (v_medium ** 3)
            tug_fuel[k] += psi

        # Transit fuel: depot → s0, then arc-by-arc, then last → depot
        s0 = route[0]
        v0 = speed_values[speeds_k[0]]
        tug_fuel[k] += beta_k * HP_k * depot_to_task_distance[s0] * (v0 ** 2) / (v_medium ** 3)
        for i in range(1, len(route)):
            si_prev, si = route[i - 1], route[i]
            v_i = speed_values[speeds_k[i]]
            d_ij = task_to_task_distance[si_prev][si]
            tug_fuel[k] += beta_k * HP_k * d_ij * (v_i ** 2) / (v_medium ** 3)
        # Return to depot
        s_last = route[-1]
        v_ret = speed_values[speeds_k[-1]]
        tug_fuel[k] += beta_k * HP_k * task_to_depot_distance[s_last] * (v_ret ** 2) / (v_medium ** 3)

        if tug_fuel[k] > tugboat_fuel_capacity[k] + EPS:
            raise Exception(
                f"tug {k} total fuel {tug_fuel[k]} > capacity "
                f"{tugboat_fuel_capacity[k]} (C13)")

    # ─── Cost computation (all constraints passed) ─────────────────────────
    service_fuel = 0.0
    for s in executed_tasks:
        d_s = task_service_distance[s]
        v_ls = speed_values[service_speeds[s]]
        for k in task_tugboats[s]:
            HP_k = tugboat_horsepower[k]
            alpha_k = tugboat_alpha[k]
            service_fuel += alpha_k * HP_k * d_s * (v_ls ** 2) / (v_medium ** 3)

    transit_fuel = 0.0
    for k in range(m):
        route = routes[k]
        if not route:
            continue
        speeds_k = transit_speeds[k]
        HP_k = tugboat_horsepower[k]
        beta_k = tugboat_beta[k]
        s0 = route[0]
        v0 = speed_values[speeds_k[0]]
        transit_fuel += beta_k * HP_k * depot_to_task_distance[s0] * (v0 ** 2) / (v_medium ** 3)
        for i in range(1, len(route)):
            si_prev, si = route[i - 1], route[i]
            v_i = speed_values[speeds_k[i]]
            d_ij = task_to_task_distance[si_prev][si]
            transit_fuel += beta_k * HP_k * d_ij * (v_i ** 2) / (v_medium ** 3)
        s_last = route[-1]
        v_ret = speed_values[speeds_k[-1]]
        transit_fuel += beta_k * HP_k * task_to_depot_distance[s_last] * (v_ret ** 2) / (v_medium ** 3)

    unexecuted = n - len(executed_tasks)
    penalty = W * unexecuted

    return float(service_fuel + transit_fuel + penalty)
