"""CO-Bench-style config for the Port Scheduling Problem (PSP).

This file is the single source of truth that the cobench spec builder consumes.

  - DESCRIPTION  → spec.description (LLM prompt: problem statement)
  - solve()      → spec.starter_code (LLM prompt: function signature + I/O schema)
  - load_data()  → spec.load_data (parses one .txt instance file → [instance_dict])
  - eval_func()  → spec.tools.is_feasible + spec.tools.objective (its SOURCE is
                   shown verbatim in the LLM prompt's feasibility section, so it
                   doubles as the constraint specification).

PSP is a hand-authored CO-Bench problem (no reference paper / known optima),
generated by problems/cobench/psp/build_instances.py.
"""

import ast


DESCRIPTION = """\
Port Scheduling Problem (PSP)

At a port operating over a discrete horizon of T time periods, n vessels
arrive over time, each requesting a berth for cargo operations. The port
has J berths of varying capacities and K tugboats of varying horsepower.
Each vessel that is served must receive THREE sequential services on the
same timeline:

    inbound tugboat tow  →  berth occupation  →  outbound tugboat tow

A defining property: you may CHOOSE TO LEAVE SOME VESSELS UNASSIGNED.
That is a legal decision; it simply forfeits servicing that vessel at the
cost of a large per-vessel penalty (Z₁ below). The decision space
therefore covers BOTH "which vessels to serve" AND "how to schedule the
ones you serve". Doing nothing (serving no vessel) is feasible — just
expensive.

────────────────────────────────────────────────────────────
Decisions (for each vessel i ∈ {0..n-1})
────────────────────────────────────────────────────────────
Either leave i unassigned, OR commit to ALL of the following together:
  • a berth j with capacity Cⱼ ≥ Sᵢ
  • an inbound start time t_in ∈ [ETAᵢ − Δᵢᵉᵃʳˡʸ, ETAᵢ + Δᵢˡᵃᵗᵉ]
  • a berth start time t_b following inbound completion (see C14)
  • an outbound start time t_out following berth completion (see C15)
  • 1..H_max inbound tugboats, total horsepower ≥ Pᵢʳᵉᵠ, ALL starting at t_in
  • 1..H_max outbound tugboats, total horsepower ≥ Pᵢʳᵉᵠ, ALL starting at t_out

────────────────────────────────────────────────────────────
Objective:   minimize   Z = λ₁·Z₁ + λ₂·Z₂ + λ₃·Z₃ + λ₄·Z₄
(LOWER IS BETTER)
────────────────────────────────────────────────────────────

  Z₁ = Σᵢ  M · αᵢ · 𝟙[vessel i is unassigned]
       Unserved-vessel penalty. M is large, so dropping a vessel is
       expensive but sometimes unavoidable (capacity / time-window
       infeasibility). αᵢ is the vessel's priority weight — high-priority
       vessels hurt more to drop.

  Z₂ = Σᵢ_assigned  αᵢ · βᵢ · ( (t_outᵢ + τᵢᵒᵘᵗ) − t_inᵢ )
       Total port-time cost: the wall-clock duration vessel i occupies
       the port system, from inbound start to outbound end. Weighted by
       priority αᵢ and per-period waiting cost βᵢ. Encourages tight,
       back-to-back scheduling of the three service stages.

  Z₃ = Σᵢ_assigned  αᵢ · γᵢ · | t_inᵢ − ETAᵢ |
       Just-in-time (JIT) deviation: penalize starting inbound service
       earlier or later than the vessel's ETA. γᵢ is the per-period JIT
       cost. Encourages on-time arrival servicing.

  Z₄ = Σ over every (tugboat k, service s) pair  cₖ · τᵢˢ
       Tugboat utilization cost. cₖ is tugboat k's per-period cost, τᵢˢ
       is the service duration (in or out) for vessel i. Encourages
       using fewer / cheaper tugboats per service.

The four terms pull against each other: Z₁ pushes toward serving MORE
vessels, but every served vessel then contributes Z₂/Z₃/Z₄. The λ
weights set the trade-off — they are given in the instance.

────────────────────────────────────────────────────────────
Constraints (must hold whenever a vessel is assigned)
────────────────────────────────────────────────────────────

— Assignment & compatibility
  (C1)  Each vessel is served at most once.
        Σⱼ,ₜ x_ijt ≤ 1 for all i.
  (C2)  A vessel can only go to a berth that is large enough.
        x_ijt = 0 whenever Cⱼ < Sᵢ.

— Service coupling: assigning a vessel forces both tug services
  (C3)  If i is assigned to any berth, it receives exactly one inbound
        tug service.            Σₜ z^in_it = Σⱼ,ₜ x_ijt.
  (C4)  Same for outbound.      Σₜ z^out_it = Σⱼ,ₜ x_ijt.

— Tugboat capability per service
  (C5)  Total horsepower of inbound tugs ≥ vessel's required horsepower.
        Σₖ Pₖ · y^in_ikt ≥ Pᵢʳᵉᵠ · z^in_it.
  (C6)  Same for outbound.
  (C7)  At most H_max tugs per inbound service.
        Σₖ y^in_ikt ≤ H_max · z^in_it.
  (C8)  Same for outbound.

— Simultaneity (easy to miss): all tugs in one service share a start
  (C9)  Every tugboat assigned to vessel i's inbound service starts at
        the SAME time t_inᵢ.
  (C10) Same for outbound — all outbound tugs start at t_outᵢ.

— Resource non-overlap (with preparation time on tugs)
  (C11) Each berth holds at most one vessel at any time, factoring in
        the vessel's berth duration Dᵢ.
  (C12) Each tugboat performs at most one service at a time, INCLUDING
        its preparation time ρⁱⁿ / ρᵒᵘᵗ after each completed service.

— Time windows
  (C13) Inbound service must start within the vessel's ETA window:
        ETAᵢ − Δᵢᵉᵃʳˡʸ ≤ t_inᵢ ≤ ETAᵢ + Δᵢˡᵃᵗᵉ.

— Sequence with bounded slack (note: ε_time is NOT zero, NOT unbounded)
  (C14) Berth occupation must start AFTER inbound completes, with a
        gap of at most ε_time periods:
        0 ≤ t_bᵢ − (t_inᵢ + τᵢⁱⁿ) ≤ ε_time.
  (C15) Outbound tug must start AFTER berth release, with the same
        bounded gap:
        0 ≤ t_outᵢ − (t_bᵢ + Dᵢ) ≤ ε_time.

(C16 and C17 are ETA-deviation linearization and variable-domain
declarations from the original MILP; they are automatically satisfied
when (C1)–(C15) and the data types are respected, so they do not appear
as separate checks.)

────────────────────────────────────────────────────────────
Notes
────────────────────────────────────────────────────────────
• The "do-nothing" solution (every vessel unassigned) is feasible and
  yields Z = λ₁ · M · Σᵢ αᵢ. Any candidate worth submitting should beat
  it. A strong heuristic decides for each vessel whether the achievable
  Z₂+Z₃+Z₄ for a feasible (in-berth-out) triple is cheaper than the
  M·αᵢ cost of skipping that vessel.

• Tooling: the `tools` dict (see the "Available tools" section) provides
  `is_feasible`, `objective`, plus helpers for finding tug combinations
  and feasible (berth, time, tugs) triples. Use them rather than
  rewriting feasibility logic from scratch.
"""


def solve(**kwargs):
    """Solve a Port Scheduling Problem (PSP) instance.

    Args (keyword arguments — instance dict unpacked):

    ────── Dimensions ──────
        vessel_num   (int): n, number of vessels.
        berth_num    (int): J, number of berths.
        tugboat_num  (int): K, number of tugboats.
        time_periods (int): T, discrete time periods in the planning horizon.

    ────── Per-vessel arrays (length n, indexed by vessel i ∈ [0, n)) ──────
        vessel_sizes                    (list[int]):   Sᵢ — size level.
        vessel_etas                     (list[int]):   ETAᵢ — expected arrival period.
        vessel_durations                (list[int]):   Dᵢ — berthing duration.
        vessel_inbound_service_times    (list[int]):   τⁱⁿᵢ — inbound tug service duration.
        vessel_outbound_service_times   (list[int]):   τᵒᵘᵗᵢ — outbound tug service duration.
        vessel_priority_weights         (list[float]): αᵢ — priority weight.
        vessel_waiting_costs            (list[float]): βᵢ — per-period waiting cost.
        vessel_jit_costs                (list[float]): γᵢ — per-period JIT deviation cost.
        vessel_horsepower_requirements  (list[int]):   Pⁱʳᵉᵠ — minimum total tug HP required.
        vessel_early_limits             (list[int]):   Δⁱᵉᵃʳˡʸ — max periods early vs ETA.
        vessel_late_limits              (list[int]):   Δⁱˡᵃᵗᵉ — max periods late vs ETA.

    ────── Per-berth arrays (length J, indexed by berth j ∈ [0, J)) ──────
        berth_capacities (list[int]): Cⱼ — capacity level. Vessel i fits at berth j iff Cⱼ ≥ Sᵢ.

    ────── Per-tugboat arrays (length K, indexed by tug k ∈ [0, K)) ──────
        tugboat_horsepower (list[int]):   Pₖ — horsepower of tug k.
        tugboat_costs      (list[float]): cₖ — per-period usage cost of tug k.

    ────── System parameters ──────
        inbound_preparation_time   (int):         ρⁱⁿ — periods of prep after inbound service.
        outbound_preparation_time  (int):         ρᵒᵘᵗ — periods of prep after outbound service.
        max_tugboats_per_service   (int):         H_max — max tugs per single service.
        time_constraint_tolerance  (int):         ε_time — max gap between sequential service stages.
        penalty_parameter          (float):       M — unserved vessel penalty.
        objective_weights          (list[float]): [λ₁, λ₂, λ₃, λ₄] — four weights for Z₁..Z₄.

    Returns:
        dict with EXACTLY these 3 keys. Each value is a dict[int, ...] whose
        keys MUST be the full range {0, 1, ..., n-1} — one entry per vessel,
        including the ones you choose to leave unassigned.

        'vessel_assignments' (dict[int, list | None]): for vessel i, the value is
            • None              — vessel i is unassigned (pays Z₁ penalty M·αᵢ)
            • [berth_id, t_b]   — vessel i berthed at berth_id ∈ [0,J),
                                  berth_start_time t_b ∈ [0,T).

        'inbound_tugboats' (dict[int, list]): for vessel i, the value is
            • []                                  — when vessel i is unassigned
            • [[k₁, t_in], [k₂, t_in], ...]       — when assigned.
              Length ∈ [1, H_max]. ALL pairs share the SAME t_in (C9).
              Σ tugboat_horsepower[kⱼ] ≥ vessel_horsepower_requirements[i]  (C5).

        'outbound_tugboats' (dict[int, list]): same shape and rules as
              inbound_tugboats, all pairs sharing t_out (C10).

    Example (n=3, vessel 0 served at berth 0, vessels 1 & 2 unassigned):
        {
          'vessel_assignments': {0: [0, 3], 1: None, 2: None},
          'inbound_tugboats':   {0: [[1, 2], [2, 2]], 1: [], 2: []},
          'outbound_tugboats':  {0: [[0, 6]],         1: [], 2: []},
        }

    The "do nothing" return below is FEASIBLE — it just pays maximum Z₁. A strong
    solver serves as many high-priority vessels as it can while respecting all 13
    constraints (see eval_func source for the exact check).
    """
    n = kwargs["vessel_num"]
    return {
        "vessel_assignments": {i: None for i in range(n)},
        "inbound_tugboats":   {i: []   for i in range(n)},
        "outbound_tugboats":  {i: []   for i in range(n)},
    }


def load_data(file_path):
    """Parse one PSP instance text file.

    Returns a list of instance dicts. PSP stores ONE instance per file, so the
    returned list always has length 1. (CO-Bench convention permits multiple
    instances per file; PSP doesn't use that.)
    """
    inst = {}
    with open(file_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, val = line.split("=", 1)
            inst[key.strip()] = ast.literal_eval(val.strip())
    return [inst]


# ============================================================================
# eval_func — Source shown verbatim to the LLM in the feasibility prompt section.
# Every `raise Exception` is a constraint a solution must NOT trip.
# ============================================================================

def eval_func(
    # --- Dimensions ---
    vessel_num, berth_num, tugboat_num, time_periods,
    # --- Per-vessel arrays (length n) ---
    vessel_sizes, vessel_etas, vessel_durations,
    vessel_inbound_service_times, vessel_outbound_service_times,
    vessel_priority_weights, vessel_waiting_costs, vessel_jit_costs,
    vessel_horsepower_requirements,
    vessel_early_limits, vessel_late_limits,
    # --- Per-berth array (length J) ---
    berth_capacities,
    # --- Per-tugboat arrays (length K) ---
    tugboat_horsepower, tugboat_costs,
    # --- System parameters ---
    inbound_preparation_time, outbound_preparation_time,
    max_tugboats_per_service, time_constraint_tolerance,
    penalty_parameter, objective_weights,
    # --- Solution keys ---
    vessel_assignments, inbound_tugboats, outbound_tugboats,
):
    """Evaluate a PSP solution.

    Raises Exception (with a descriptive message) if any of the 13 active
    constraints is violated. Otherwise returns the float objective
    Z = λ₁·Z₁ + λ₂·Z₂ + λ₃·Z₃ + λ₄·Z₄  (LOWER IS BETTER).
    """
    n = vessel_num
    J = berth_num
    K = tugboat_num
    T = time_periods
    H_max = max_tugboats_per_service
    eps_time = time_constraint_tolerance
    rho_in = inbound_preparation_time
    rho_out = outbound_preparation_time

    # ─── Top-level shape ───────────────────────────────────────────────────
    expected_keys = set(range(n))
    if not isinstance(vessel_assignments, dict) or set(vessel_assignments.keys()) != expected_keys:
        raise Exception(
            f"vessel_assignments must be dict with keys exactly {{0..{n-1}}}, "
            f"got type={type(vessel_assignments).__name__}")
    if not isinstance(inbound_tugboats, dict) or set(inbound_tugboats.keys()) != expected_keys:
        raise Exception(
            f"inbound_tugboats must be dict with keys exactly {{0..{n-1}}}, "
            f"got type={type(inbound_tugboats).__name__}")
    if not isinstance(outbound_tugboats, dict) or set(outbound_tugboats.keys()) != expected_keys:
        raise Exception(
            f"outbound_tugboats must be dict with keys exactly {{0..{n-1}}}, "
            f"got type={type(outbound_tugboats).__name__}")

    # ─── Per-vessel validation ─────────────────────────────────────────────
    for i in range(n):
        va = vessel_assignments[i]
        ib = inbound_tugboats[i]
        ob = outbound_tugboats[i]

        if va is None:
            # (C3/C4 for unassigned i): no tug services allowed
            if ib:
                raise Exception(f"vessel {i} unassigned but inbound_tugboats[{i}]={ib}")
            if ob:
                raise Exception(f"vessel {i} unassigned but outbound_tugboats[{i}]={ob}")
            continue

        # Assigned vessel — strict shape
        if not (isinstance(va, list) and len(va) == 2):
            raise Exception(
                f"vessel_assignments[{i}] must be None or [berth_id, t_b], got {va!r}")
        berth_id, t_b = va
        if not isinstance(berth_id, int) or not (0 <= berth_id < J):
            raise Exception(f"vessel {i} berth_id={berth_id} not in [0, {J})")
        if not isinstance(t_b, int) or not (0 <= t_b < T):
            raise Exception(f"vessel {i} berth_start_time={t_b} not in [0, {T})")

        # (C2) berth must fit vessel
        if berth_capacities[berth_id] < vessel_sizes[i]:
            raise Exception(
                f"vessel {i} size={vessel_sizes[i]} exceeds berth {berth_id} "
                f"capacity={berth_capacities[berth_id]} (C2)")

        # (C3/C4) assigned ⇒ both tug services present
        if not isinstance(ib, list) or len(ib) == 0:
            raise Exception(f"vessel {i} assigned but no inbound tug service (C3)")
        if not isinstance(ob, list) or len(ob) == 0:
            raise Exception(f"vessel {i} assigned but no outbound tug service (C4)")

        # (C7) at most H_max inbound tugs
        if len(ib) > H_max:
            raise Exception(
                f"vessel {i} uses {len(ib)} inbound tugs > H_max={H_max} (C7)")
        # (C8) at most H_max outbound tugs
        if len(ob) > H_max:
            raise Exception(
                f"vessel {i} uses {len(ob)} outbound tugs > H_max={H_max} (C8)")

        # Validate every tug pair shape + indices
        def _check_pairs(pairs, kind):
            for p in pairs:
                if not (isinstance(p, list) and len(p) == 2):
                    raise Exception(
                        f"vessel {i} {kind}_tugboats entry must be [tug_id, t], got {p!r}")
                k_, t_ = p
                if not isinstance(k_, int) or not (0 <= k_ < K):
                    raise Exception(f"vessel {i} {kind} tug_id={k_} not in [0, {K})")
                if not isinstance(t_, int) or not (0 <= t_ < T):
                    raise Exception(f"vessel {i} {kind} t={t_} not in [0, {T})")
        _check_pairs(ib, "inbound")
        _check_pairs(ob, "outbound")

        # (C9/C10) all tugs in one service share start time
        in_starts = set(t for _, t in ib)
        if len(in_starts) > 1:
            raise Exception(
                f"vessel {i} inbound tugs have inconsistent starts {in_starts} (C9)")
        out_starts = set(t for _, t in ob)
        if len(out_starts) > 1:
            raise Exception(
                f"vessel {i} outbound tugs have inconsistent starts {out_starts} (C10)")
        t_in = ib[0][1]
        t_out = ob[0][1]

        # (C5) inbound HP sum ≥ vessel requirement
        hp_in = sum(tugboat_horsepower[k_] for k_, _ in ib)
        if hp_in < vessel_horsepower_requirements[i]:
            raise Exception(
                f"vessel {i} inbound HP={hp_in} < required {vessel_horsepower_requirements[i]} (C5)")
        # (C6) outbound HP sum ≥ vessel requirement
        hp_out = sum(tugboat_horsepower[k_] for k_, _ in ob)
        if hp_out < vessel_horsepower_requirements[i]:
            raise Exception(
                f"vessel {i} outbound HP={hp_out} < required {vessel_horsepower_requirements[i]} (C6)")

        # (C13) inbound time window
        eta = vessel_etas[i]
        if not (eta - vessel_early_limits[i] <= t_in <= eta + vessel_late_limits[i]):
            raise Exception(
                f"vessel {i} t_in={t_in} outside ETA window "
                f"[{eta - vessel_early_limits[i]}, {eta + vessel_late_limits[i]}] (C13)")

        # (C14) berth_start in [inbound_end, inbound_end + ε_time]
        tau_in = vessel_inbound_service_times[i]
        gap_b = t_b - (t_in + tau_in)
        if gap_b < 0:
            raise Exception(
                f"vessel {i} berth_start={t_b} < inbound_end={t_in + tau_in} (C14)")
        if gap_b > eps_time:
            raise Exception(
                f"vessel {i} berth_start - inbound_end={gap_b} > ε_time={eps_time} (C14)")

        # (C15) outbound_start in [berth_end, berth_end + ε_time]
        D_i = vessel_durations[i]
        gap_o = t_out - (t_b + D_i)
        if gap_o < 0:
            raise Exception(
                f"vessel {i} outbound_start={t_out} < berth_end={t_b + D_i} (C15)")
        if gap_o > eps_time:
            raise Exception(
                f"vessel {i} outbound_start - berth_end={gap_o} > ε_time={eps_time} (C15)")

        # Outbound must complete by T
        tau_out = vessel_outbound_service_times[i]
        if t_out + tau_out > T:
            raise Exception(
                f"vessel {i} outbound_end={t_out + tau_out} exceeds T={T}")

    # ─── Cross-vessel resource constraints ─────────────────────────────────

    # (C11) berth non-overlap
    berth_occ = {j: [] for j in range(J)}
    for i in range(n):
        va = vessel_assignments[i]
        if va is None:
            continue
        bj, t_b = va
        berth_occ[bj].append((t_b, t_b + vessel_durations[i], i))
    for bj, occs in berth_occ.items():
        occs.sort()
        for u in range(len(occs) - 1):
            if occs[u][1] > occs[u + 1][0]:
                raise Exception(
                    f"berth {bj} conflict: vessel {occs[u][2]} ends at {occs[u][1]} "
                    f"but vessel {occs[u + 1][2]} starts at {occs[u + 1][0]} (C11)")

    # (C12) tugboat non-overlap (including preparation time)
    tug_occ = {k: [] for k in range(K)}
    for i in range(n):
        if vessel_assignments[i] is None:
            continue
        tau_in = vessel_inbound_service_times[i]
        tau_out = vessel_outbound_service_times[i]
        for k_, t_ in inbound_tugboats[i]:
            tug_occ[k_].append((t_, t_ + tau_in + rho_in, i, "in"))
        for k_, t_ in outbound_tugboats[i]:
            tug_occ[k_].append((t_, t_ + tau_out + rho_out, i, "out"))
    for k_, occs in tug_occ.items():
        occs.sort()
        for u in range(len(occs) - 1):
            if occs[u][1] > occs[u + 1][0]:
                raise Exception(
                    f"tugboat {k_} conflict: vessel {occs[u][2]} ({occs[u][3]}) "
                    f"busy until {occs[u][1]} but vessel {occs[u + 1][2]} "
                    f"({occs[u + 1][3]}) starts at {occs[u + 1][0]} (C12)")

    # ─── Cost computation (all constraints passed) ─────────────────────────
    lambda_1, lambda_2, lambda_3, lambda_4 = objective_weights

    z1 = 0.0  # unserved penalty
    z2 = 0.0  # port time
    z3 = 0.0  # JIT deviation
    z4 = 0.0  # tugboat utilization

    for i in range(n):
        if vessel_assignments[i] is None:
            # Z₁ = Σ M · αᵢ for unassigned i
            z1 += penalty_parameter * vessel_priority_weights[i]
            continue
        t_in = inbound_tugboats[i][0][1]
        t_out = outbound_tugboats[i][0][1]
        tau_in_i = vessel_inbound_service_times[i]
        tau_out_i = vessel_outbound_service_times[i]

        # Z₂ = Σᵢ_assigned αᵢ · βᵢ · ((t_out + τ_out) − t_in)
        port_time = (t_out + tau_out_i) - t_in
        z2 += vessel_priority_weights[i] * vessel_waiting_costs[i] * port_time

        # Z₃ = Σᵢ_assigned αᵢ · γᵢ · |t_in − ETAᵢ|
        z3 += vessel_priority_weights[i] * vessel_jit_costs[i] * abs(t_in - vessel_etas[i])

        # Z₄ = Σ over tug pairs: cₖ · τ
        for k_, _ in inbound_tugboats[i]:
            z4 += tugboat_costs[k_] * tau_in_i
        for k_, _ in outbound_tugboats[i]:
            z4 += tugboat_costs[k_] * tau_out_i

    return float(lambda_1 * z1 + lambda_2 * z2 + lambda_3 * z3 + lambda_4 * z4)
