#!/usr/bin/env python3
"""
Reproduce the MACE vs. AFL comparison on TSPLIB (Reviewer 1, Comment 2).

Both methods solve the same 16 TSPLIB instances under an identical 10-second
per-instance wall-clock budget, and we report the tour length and the gap to the
known optimum (lower is better).

  * MACE : its shipped 10-heuristic TSP portfolio (no LLM call at solve time).
  * AFL  : a TSP solver generated by AFL's own pipeline (AFL ships no TSP solver;
           see afl_solver/ and the README). Run with a wall-clock budget so the
           time budget matches MACE exactly.

Usage
-----
    # Point at a checkout of the MACE repository (https://github.com/PJ-NTU/MACE)
    python run_comparison.py --mace-repo /path/to/MACE

Requirements: numpy, scipy (the MACE portfolio's dependencies). No API key needed.
"""
import argparse
import glob
import importlib
import os
import re
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
TSPLIB_DIR = os.path.join(HERE, "tsplib")
AFL_SOLVER = os.path.join(HERE, "afl_solver", "afl_tsp_solver.py")

# TSPLIB published optimal tour lengths (used only to report the gap).
OPT = {
    "eil51": 426, "berlin52": 7542, "st70": 675, "eil101": 629, "pr144": 58537,
    "kroA150": 26524, "ch150": 6528, "rat195": 2323, "kroA200": 29368,
    "pr226": 80369, "a280": 2579, "lin318": 42029, "pr439": 107217,
    "pcb442": 50778, "d493": 35002, "pr1002": 259045,
}


def parse_tsplib(path):
    """Read a TSPLIB EUC_2D file into a list of (x, y) coordinates."""
    nodes, in_sec = [], False
    for line in open(path):
        line = line.strip()
        if line.startswith("NODE_COORD_SECTION"):
            in_sec = True
            continue
        if line.startswith("EOF") or not line or line.startswith("DISPLAY"):
            continue
        if in_sec:
            p = line.split()
            if len(p) >= 3:
                try:
                    nodes.append((float(p[1]), float(p[2])))
                except ValueError:
                    pass
    return nodes


def load_mace_portfolio(mace_repo):
    """Load MACE's shipped TSP portfolio (10 heuristics) and its solve harness."""
    sys.path.insert(0, mace_repo)
    from mace.framework import run_solve, load_heuristic  # noqa: E402
    spec = importlib.import_module(
        "problems.travelling_salesman_problem.spec").SPEC
    paths = sorted(glob.glob(os.path.join(
        mace_repo, "problems", "travelling_salesman_problem",
        "portfolio", "heuristic_*.py")))
    heurs = [load_heuristic(p) for p in paths]
    return run_solve, spec, heurs


def mace_best(run_solve, spec, heurs, nodes, tmax):
    """Best tour length across MACE's portfolio; each heuristic gets tmax seconds."""
    inst = {"nodes": nodes, "label_tour": None}
    best = None
    for fn in heurs:
        try:
            r = run_solve(spec, inst, fn, time_limit_s=tmax)
            if r.feasible and (best is None or r.objective < best):
                best = r.objective
        except Exception:
            pass
    return best


def afl_best(tsp_path, tmax):
    """Best tour length from the AFL solver, run for exactly tmax wall-clock seconds."""
    try:
        r = subprocess.run(
            [sys.executable, AFL_SOLVER, "--path", tsp_path,
             "--time-limit", str(tmax)],
            capture_output=True, text=True, timeout=tmax + 30)
        m = re.search(r"best cost is (\d+\.?\d*)", r.stdout)
        return float(m.group(1)) if m else None
    except subprocess.TimeoutExpired:
        return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mace-repo", required=True,
                    help="path to a checkout of the MACE repository")
    ap.add_argument("--tmax", type=float, default=10.0,
                    help="per-instance wall-clock budget in seconds (default 10)")
    args = ap.parse_args()

    run_solve, spec, heurs = load_mace_portfolio(args.mace_repo)
    insts = sorted(glob.glob(os.path.join(TSPLIB_DIR, "*.tsp")),
                   key=lambda p: len(parse_tsplib(p)))

    hdr = f"{'instance':<10}{'n':>6}{'opt':>9}{'MACE':>11}{'AFL':>11}{'MACE%':>9}{'AFL%':>9}{'win':>7}"
    print(hdr)
    print("-" * len(hdr))
    mace_gaps, afl_gaps, mace_wins = [], [], 0
    for path in insts:
        name = os.path.basename(path)[:-4]
        nodes = parse_tsplib(path)
        opt = OPT.get(name)
        mb = mace_best(run_solve, spec, heurs, nodes, args.tmax)
        ab = afl_best(path, args.tmax)
        if mb is None or ab is None:
            print(f"{name:<10}{len(nodes):>6}{opt or '?':>9}"
                  f"{str(mb):>11}{str(ab):>11}")
            continue
        mg, ag = (mb / opt - 1) * 100, (ab / opt - 1) * 100
        win = "MACE" if mb < ab else ("AFL" if ab < mb else "tie")
        mace_wins += (mb <= ab)
        mace_gaps.append(mg)
        afl_gaps.append(ag)
        print(f"{name:<10}{len(nodes):>6}{opt:>9}{mb:>11.1f}{ab:>11.1f}"
              f"{mg:>8.2f}%{ag:>8.2f}%{win:>7}")

    if mace_gaps:
        print("-" * len(hdr))
        print(f"{'AVERAGE':<10}{'':>6}{'':>9}{'':>11}{'':>11}"
              f"{sum(mace_gaps)/len(mace_gaps):>8.2f}%"
              f"{sum(afl_gaps)/len(afl_gaps):>8.2f}%"
              f"{f'{mace_wins}/{len(mace_gaps)}':>7}")


if __name__ == "__main__":
    main()
